// Generated by MyKStars edition engine v1.0.0.
// Inventory SHA-256: 9c9b23206464583bb0210f2d9d65a3aa301f9077ba2517a42d194286654fa9d2
// Regenerate with npm run gen:edition. Do not hand-edit this artifact.
import type { FeedEdition } from "../../lib/types";

export const edition202607: FeedEdition = {
  "id": "2026-07",
  "publishedAt": "2026-07-15T20:00:00+09:00",
  "bands": [
    {
      "kind": "hero",
      "clipId": "clip-tv-roh-yoon-seo-nam-joo-hyuk-asianfeed"
    },
    {
      "kind": "forecast-rail",
      "predictionSlugs": [
        "cortis-greengreen-ten-weeks-billboard",
        "byeon-woo-seok-netflix-top10-july",
        "newjeans-return-official-word-2026"
      ]
    },
    {
      "kind": "analysis",
      "pillar": "k-pop",
      "articleSlugs": [
        "katseye-wild-catalogue-win"
      ]
    },
    {
      "kind": "ranking",
      "slug": "drama-viewership"
    },
    {
      "kind": "event-rail",
      "eventSlugs": [
        "stray-kids-world-tour-seoul-aug-1-2",
        "enhypen-blood-saga-oakland",
        "stray-kids-world-tour-seoul-jul-29",
        "ive-show-what-i-am-newark",
        "stray-kids-world-tour-seoul",
        "cortis-put-your-phone-down-incheon",
        "bts-arirang-paris",
        "iu-world-tour-newark"
      ]
    },
    {
      "kind": "clip-rail",
      "title": "Now playing",
      "description": "Current official videos from across MyKStars.",
      "clipIds": [
        "clip-tv-kim-min-ha-jtbc-news",
        "clip-yt-twice-what-is-love-tokyo-dome"
      ]
    },
    {
      "kind": "analysis",
      "pillar": "k-pop",
      "articleSlugs": [
        "rookie-class-2026-first-week-curve"
      ]
    },
    {
      "kind": "pulse-band",
      "pulseSlugs": [
        "2026-07-ive-circle-midyear",
        "2026-07-park-eun-bin-spooky-in-love-press-conference",
        "2026-07-jung-hoyeon-hope-press-screening",
        "2026-07-cortis-circle-midyear"
      ]
    },
    {
      "kind": "clip-rail",
      "title": "Now playing",
      "description": "Current official videos from across MyKStars.",
      "clipIds": [
        "clip-tv-choo-young-woo-pickcon",
        "clip-yt-ateez-bad"
      ]
    },
    {
      "kind": "clip-rail",
      "title": "Now playing",
      "description": "Current official videos from across MyKStars.",
      "clipIds": [
        "clip-tv-jung-hoyeon-pinggyego",
        "clip-yt-meovv-ddi-ro-ri"
      ]
    },
    {
      "kind": "ranking",
      "slug": "idol-brand-reputation"
    },
    {
      "kind": "clip-rail",
      "title": "Now playing",
      "description": "Current official videos from across MyKStars.",
      "clipIds": [
        "clip-yt-enhypen-well-be-fine",
        "clip-tv-cha-eunwoo-wonderfools"
      ]
    },
    {
      "kind": "analysis",
      "pillar": "k-movie",
      "articleSlugs": [
        "festival-circuit-explained"
      ]
    },
    {
      "kind": "clip-rail",
      "title": "Now playing",
      "description": "Current official videos from across MyKStars.",
      "clipIds": [
        "clip-yt-seventeen-v8-singasong",
        "clip-tv-byeon-woo-seok-iu-pinggyego"
      ]
    },
    {
      "kind": "pulse-band",
      "pulseSlugs": [
        "2026-07-twice-stray-kids-recording-academy",
        "2026-07-east-palace-press-conference",
        "2026-07-kim-min-ha-hana-korea-interview",
        "2026-07-blackpink-jennie-dracula-hot-100"
      ]
    },
    {
      "kind": "clip-rail",
      "title": "Now playing",
      "description": "Current official videos from across MyKStars.",
      "clipIds": [
        "clip-yt-stray-kids-run-it",
        "clip-tv-park-eun-bin-mmtg"
      ]
    },
    {
      "kind": "spotlight-strip"
    },
    {
      "kind": "forecast-rail",
      "predictionSlugs": [
        "hearts2hearts-lemon-tang-circle-top10-august",
        "lee-min-ho-next-drama-confirmed-2026",
        "babymonster-choom-first-week-record-q3"
      ]
    },
    {
      "kind": "analysis",
      "pillar": "k-movie",
      "articleSlugs": [
        "korean-cinema-distributor-concentration"
      ]
    },
    {
      "kind": "clip-rail",
      "title": "Now playing",
      "description": "Current official videos from across MyKStars.",
      "clipIds": [
        "clip-tv-lee-chae-min-baeksang",
        "clip-yt-riize-do-your-dance"
      ]
    },
    {
      "kind": "pulse-band",
      "pulseSlugs": [
        "2026-07-twice-tour-finale-seoul",
        "2026-07-byeon-woo-seok-secret-library-seoul",
        "2026-07-rookie-groups-circle-midyear",
        "2026-07-illit-aespa-hanteo-country-charts"
      ]
    },
    {
      "kind": "clip-rail",
      "title": "Now playing",
      "description": "Current official videos from across MyKStars.",
      "clipIds": [
        "clip-yt-nmixx-heavy-serenade",
        "clip-tv-park-chan-wook-mygeumhee"
      ]
    },
    {
      "kind": "forecast-rail",
      "predictionSlugs": [
        "bts-arirang-global-top10-summer",
        "kim-tae-ri-next-role-announced-2026",
        "iu-new-album-august-2026"
      ]
    },
    {
      "kind": "analysis",
      "pillar": "k-pop",
      "articleSlugs": [
        "ateez-number-one-listening-test"
      ]
    },
    {
      "kind": "clip-rail",
      "title": "Now playing",
      "description": "Current official videos from across MyKStars.",
      "clipIds": [
        "clip-yt-boynextdoor-viral",
        "clip-tv-kim-seon-ho-bazaar"
      ]
    },
    {
      "kind": "pulse-band",
      "pulseSlugs": [
        "2026-07-le-sserafim-pureflow-incheon",
        "2026-07-seventeen-v8-goyang-live",
        "2026-07-hearts2hearts-music-station-debut",
        "2026-07-bts-london-return"
      ]
    },
    {
      "kind": "clip-rail",
      "title": "On air",
      "description": "Talk, comedy and variety appearances on official channels.",
      "clipIds": [
        "clip-tv-ahn-hyo-seop-fairy-jaehyung",
        "clip-tv-aespa-aesparty"
      ]
    },
    {
      "kind": "forecast-rail",
      "predictionSlugs": [
        "ive-seventh-all-kill-tour-window",
        "blackpink-daesang-mama-2026",
        "cha-eunwoo-post-service-comeback-2026"
      ]
    },
    {
      "kind": "analysis",
      "pillar": "k-pop",
      "articleSlugs": [
        "jyp-tour-shop-release-calendar"
      ]
    },
    {
      "kind": "clip-rail",
      "title": "In motion",
      "description": "Official music videos and performances.",
      "clipIds": [
        "clip-yt-aespa-wda",
        "clip-yt-cortis-tnt"
      ]
    },
    {
      "kind": "pulse-band",
      "pulseSlugs": [
        "2026-07-bts-british-museum-gallery-trail",
        "2026-07-babymonster-i-like-it-video",
        "2026-07-hearts2hearts-lemon-tang-first-win",
        "2026-07-ateez-golden-hour-part5-first-week"
      ]
    },
    {
      "kind": "clip-rail",
      "title": "In motion",
      "description": "Official music videos and performances.",
      "clipIds": [
        "clip-yt-katseye-pinky-up",
        "clip-yt-babymonster-choom"
      ]
    },
    {
      "kind": "clip-rail",
      "title": "In motion",
      "description": "Official music videos and performances.",
      "clipIds": [
        "clip-yt-le-sserafim-boompala",
        "clip-yt-allday-project-pubg"
      ]
    }
  ],
  "spotlight": {
    "anchors": [
      "illit",
      "newjeans",
      "choo-young-woo",
      "aespa",
      "twice",
      "cha-eunwoo",
      "enhypen",
      "meovv",
      "kim-tae-ri",
      "riize",
      "jung-hoyeon",
      "park-ji-hu"
    ],
    "weeks": [
      [
        "kim-seon-ho",
        "roh-yoon-seo",
        "boynextdoor",
        "park-chan-wook",
        "iu",
        "ateez",
        "bts"
      ],
      [
        "byeon-woo-seok",
        "bong-joon-ho",
        "le-sserafim",
        "han-so-hee",
        "allday-project",
        "stray-kids",
        "cortis"
      ],
      [
        "kim-min-ha",
        "nam-joo-hyuk",
        "seventeen",
        "nmixx",
        "katseye",
        "lee-chae-min",
        "babymonster"
      ],
      [
        "ive",
        "lee-min-ho",
        "tws",
        "ahn-hyo-seop",
        "hearts2hearts",
        "park-eun-bin",
        "blackpink"
      ]
    ]
  }
};
