// Generated by MyKStars edition engine v2.0.0.
// Inventory SHA-256: 4150d4212d2edd405e890d0f81d85478ee423ab65d10fb8feace9bee89895e48
// Regenerate with npm run gen:edition. Do not hand-edit this artifact.
import type { FeedEdition } from "../../lib/types";

export const edition202607: FeedEdition = {
  "id": "2026-07",
  "publishedAt": "2026-07-16T20:00:00+09:00",
  "bands": [
    {
      "kind": "hero",
      "clipId": "clip-tv-roh-yoon-seo-nam-joo-hyuk-asianfeed"
    },
    {
      "kind": "forecast-rail",
      "predictionSlugs": [
        "iu-new-album-august-2026",
        "byeon-woo-seok-netflix-top10-july",
        "bts-arirang-global-top10-summer"
      ]
    },
    {
      "kind": "analysis",
      "pillar": "k-pop",
      "articleSlugs": [
        "yg-concert-accessibility-standard"
      ]
    },
    {
      "kind": "ranking",
      "slug": "drama-viewership"
    },
    {
      "kind": "event-rail",
      "eventSlugs": [
        "stray-kids-world-tour-seoul-aug-1-2",
        "cortis-lollapalooza-chicago",
        "stray-kids-world-tour-seoul-jul-29",
        "enhypen-blood-saga-oakland",
        "stray-kids-world-tour-seoul",
        "ive-show-what-i-am-newark",
        "bts-arirang-paris",
        "cortis-put-your-phone-down-incheon"
      ]
    },
    {
      "kind": "clip-rail",
      "presentation": "variety",
      "clipIds": [
        "clip-tv-kim-min-ha-jtbc-news",
        "clip-tv-aespa-aesparty"
      ]
    },
    {
      "kind": "analysis",
      "pillar": "k-movie",
      "articleSlugs": [
        "festival-circuit-explained"
      ]
    },
    {
      "kind": "pulse-band",
      "pulseSlugs": [
        "2026-07-cortis-circle-midyear",
        "2026-07-park-eun-bin-spooky-in-love-press-conference",
        "2026-07-jung-hoyeon-hope-press-screening",
        "2026-07-rookie-groups-circle-midyear"
      ]
    },
    {
      "kind": "clip-rail",
      "presentation": "mixed",
      "clipIds": [
        "clip-tv-choo-young-woo-pickcon",
        "clip-yt-twice-what-is-love-tokyo-dome"
      ]
    },
    {
      "kind": "clip-rail",
      "presentation": "mixed",
      "clipIds": [
        "clip-tv-jung-hoyeon-pinggyego",
        "clip-yt-seventeen-v8-singasong"
      ]
    },
    {
      "kind": "forecast-rail",
      "predictionSlugs": [
        "ive-seventh-all-kill-tour-window",
        "kim-tae-ri-next-role-announced-2026",
        "babymonster-choom-first-week-record-q3"
      ]
    },
    {
      "kind": "analysis",
      "pillar": "k-drama",
      "articleSlugs": [
        "webtoon-tv-creator-transparency"
      ]
    },
    {
      "kind": "pulse-band",
      "pulseSlugs": [
        "2026-07-twice-stray-kids-recording-academy",
        "2026-07-east-palace-press-conference",
        "2026-07-kim-min-ha-hana-korea-interview",
        "2026-07-hearts2hearts-music-station-debut"
      ]
    },
    {
      "kind": "clip-rail",
      "presentation": "mixed",
      "clipIds": [
        "clip-yt-enhypen-well-be-fine",
        "clip-tv-park-eun-bin-mmtg"
      ]
    },
    {
      "kind": "clip-rail",
      "presentation": "mixed",
      "clipIds": [
        "clip-yt-ateez-bad",
        "clip-tv-kim-seon-ho-bazaar"
      ]
    },
    {
      "kind": "analysis",
      "pillar": "k-pop",
      "articleSlugs": [
        "jyp-tour-shop-release-calendar"
      ]
    },
    {
      "kind": "spotlight-strip"
    },
    {
      "kind": "forecast-rail",
      "predictionSlugs": [
        "hearts2hearts-lemon-tang-circle-top10-august",
        "lee-min-ho-next-drama-confirmed-2026",
        "blackpink-daesang-mama-2026"
      ]
    },
    {
      "kind": "pulse-band",
      "pulseSlugs": [
        "2026-07-ive-circle-midyear",
        "2026-07-byeon-woo-seok-secret-library-seoul",
        "2026-07-blackpink-jennie-dracula-hot-100",
        "2026-07-bts-london-return"
      ]
    },
    {
      "kind": "clip-rail",
      "presentation": "mixed",
      "clipIds": [
        "clip-yt-stray-kids-run-it",
        "clip-tv-lee-chae-min-baeksang"
      ]
    },
    {
      "kind": "analysis",
      "pillar": "k-pop",
      "articleSlugs": [
        "girl-group-brand-race-2026"
      ]
    },
    {
      "kind": "clip-rail",
      "presentation": "mixed",
      "clipIds": [
        "clip-yt-boynextdoor-viral",
        "clip-tv-cha-eunwoo-wonderfools"
      ]
    },
    {
      "kind": "ranking",
      "slug": "idol-brand-reputation"
    },
    {
      "kind": "clip-rail",
      "presentation": "mixed",
      "clipIds": [
        "clip-yt-riize-do-your-dance",
        "clip-tv-byeon-woo-seok-iu-pinggyego"
      ]
    },
    {
      "kind": "pulse-band",
      "pulseSlugs": [
        "2026-07-seventeen-v8-goyang-live",
        "2026-07-twice-tour-finale-seoul",
        "2026-07-illit-aespa-hanteo-country-charts",
        "2026-07-bts-british-museum-gallery-trail"
      ]
    },
    {
      "kind": "clip-rail",
      "presentation": "mixed",
      "clipIds": [
        "clip-tv-ahn-hyo-seop-fairy-jaehyung",
        "clip-yt-nmixx-heavy-serenade"
      ]
    },
    {
      "kind": "analysis",
      "pillar": "k-movie",
      "articleSlugs": [
        "korean-cinema-southeast-asia-local-leadership"
      ]
    },
    {
      "kind": "clip-rail",
      "presentation": "music",
      "clipIds": [
        "clip-yt-le-sserafim-boompala",
        "clip-yt-meovv-ddi-ro-ri"
      ]
    },
    {
      "kind": "forecast-rail",
      "predictionSlugs": [
        "cha-eunwoo-post-service-comeback-2026",
        "cortis-greengreen-ten-weeks-billboard",
        "newjeans-return-official-word-2026"
      ]
    },
    {
      "kind": "pulse-band",
      "pulseSlugs": [
        "2026-07-le-sserafim-pureflow-incheon",
        "2026-07-ateez-golden-hour-part5-first-week",
        "2026-07-hearts2hearts-lemon-tang-first-win",
        "2026-07-babymonster-i-like-it-video"
      ]
    },
    {
      "kind": "clip-rail",
      "presentation": "music",
      "clipIds": [
        "clip-yt-aespa-wda",
        "clip-yt-babymonster-choom"
      ]
    },
    {
      "kind": "analysis",
      "pillar": "k-pop",
      "articleSlugs": [
        "sunmi-forever-july-monsoon-pop"
      ]
    },
    {
      "kind": "clip-rail",
      "presentation": "music",
      "clipIds": [
        "clip-yt-allday-project-pubg",
        "clip-yt-katseye-pinky-up"
      ]
    },
    {
      "kind": "analysis",
      "pillar": "k-pop",
      "articleSlugs": [
        "rookie-class-2026-first-week-curve"
      ]
    }
  ],
  "spotlight": {
    "anchors": [
      "illit",
      "newjeans",
      "choo-young-woo",
      "aespa",
      "twice",
      "cha-eunwoo",
      "enhypen",
      "meovv",
      "kim-tae-ri",
      "riize",
      "jung-hoyeon",
      "park-ji-hu"
    ],
    "weeks": [
      [
        "kim-seon-ho",
        "roh-yoon-seo",
        "boynextdoor",
        "park-chan-wook",
        "iu",
        "ateez",
        "bts"
      ],
      [
        "byeon-woo-seok",
        "bong-joon-ho",
        "le-sserafim",
        "han-so-hee",
        "allday-project",
        "stray-kids",
        "cortis"
      ],
      [
        "kim-min-ha",
        "nam-joo-hyuk",
        "seventeen",
        "nmixx",
        "katseye",
        "lee-chae-min",
        "babymonster"
      ],
      [
        "ive",
        "lee-min-ho",
        "tws",
        "ahn-hyo-seop",
        "hearts2hearts",
        "park-eun-bin",
        "blackpink"
      ]
    ]
  },
  "provenance": {
    "activeArtistSlugs": [
      "illit",
      "newjeans",
      "choo-young-woo",
      "aespa",
      "twice",
      "cha-eunwoo",
      "enhypen",
      "meovv",
      "kim-tae-ri",
      "riize",
      "jung-hoyeon",
      "park-ji-hu",
      "kim-seon-ho",
      "roh-yoon-seo",
      "boynextdoor",
      "park-chan-wook",
      "iu",
      "ateez",
      "bts",
      "byeon-woo-seok",
      "bong-joon-ho",
      "le-sserafim",
      "han-so-hee",
      "allday-project",
      "stray-kids",
      "cortis",
      "kim-min-ha",
      "nam-joo-hyuk",
      "seventeen",
      "nmixx",
      "katseye",
      "lee-chae-min",
      "babymonster",
      "ive",
      "lee-min-ho",
      "tws",
      "ahn-hyo-seop",
      "hearts2hearts",
      "park-eun-bin",
      "blackpink"
    ],
    "inventoryHash": "4150d4212d2edd405e890d0f81d85478ee423ab65d10fb8feace9bee89895e48"
  }
};
