import type { Article, Source } from "@/lib/types";
import { FESTIVAL, NEWS1, NEWSEN, OSEN, STAR_NEWS, STUDIO, VOGUE_KOREA } from "./sources";

const ATEEZ_BILLBOARD_WEEK_TWO: Source = {
  name: "Star News · Billboard 200 week two",
  url: "https://www.starnewskorea.com/music/2026/07/15/2026071509182154700",
  kind: "press",
};
const KATSEYE_WILD_CAMPAIGN: Source = {
  name: "Universal Music Japan · KATSEYE",
  url: "https://www.universal-music.co.jp/katseye/news/2026-05-27/",
  kind: "official",
};
const JYP_FY26_Q1: Source = {
  name: "JYP Entertainment · FY26 Q1 Earnings Note",
  url: "https://www.jype.com/Board/Detail?gubun=irdata&jbst_sq=6985",
  kind: "official",
};
const KOBIS_2026_YEARLY: Source = {
  name: "KOBIS · 2026 yearly box office",
  url: "https://www.koreanfilm.or.kr/eng/news/boxOffice_Yearly.jsp?mode=BOXOFFICE_YEAR&selectDt=2026",
  kind: "official",
};
const SUNMI_FOREVER_JULY: Source = {
  name: "The Korea Times · Sunmi 'Forever July'",
  url: "https://www.koreatimes.co.kr/entertainment/k-pop/20260715/sunmi-returns-with-rainy-summer-single-forever-july",
  kind: "press",
};
const YG_CONCERT_ACCESSIBILITY: Source = {
  name: "YG Entertainment · 2026 Sustainable Concert Report",
  url: "https://ygfamily.com/contents/attachments/2026/06/YG_Entertainment_2026_%2BSustainable%2BConcert%2BReport_ENG.pdf",
  kind: "official",
};
const KOCCA_2025_WEBTOON_SURVEY: Source = {
  name: "KOCCA · 2025 Webtoon Industry Survey, public edition",
  url: "https://welcon.kocca.kr/ko/info/report/1956900",
  kind: "official",
};
const KOFIC_SOUTHEAST_ASIA_STRATEGY: Source = {
  name: "KOFIC · Southeast Asia co-production strategy",
  url: "https://magazine.kofic.or.kr/webzine/web2/2833/pdsView.do",
  kind: "official",
};

// ---------------------------------------------------------------------------
// ARTICLES
// ---------------------------------------------------------------------------
export const articles: Article[] = [
  // 2026-07-16 reactive Analysis run
  {
    slug: "sunmi-forever-july-monsoon-pop",
    title: "Sunmi makes the monsoon a summer-pop advantage",
    dek: "'Forever July' treats rain, humidity and uncertainty as the season's real texture. Its chart life will test whether cultural precision can create durable pop demand.",
    status: "analysis",
    pillar: "k-pop",
    author: "MyKStars",
    date: "2026-07-16T14:30:00+09:00",
    body: [
      "Sunmi's 'Forever July' makes a bullish bet on cultural precision. The single uses monsoon rain, wet air and emotional uncertainty as the sound and image of a Korean summer. That choice gives a veteran soloist a sharper position than another bright seasonal hook. The song can become a durable summer record because it names the season people actually live through.",
      "*The Korea Times* reported on July 15, 2026, that 'Forever July' arrived eight months after Sunmi's first full-length album, *Heart Maid*. Abyss Company described the song as a love story shaped by a sudden downpour. A UK garage rhythm carries the track, and Sunmi took part in both writing and composing it. The concept, sound and authorship therefore point in the same direction.",
      "Her earlier summer records give the idea a credible base. The same July 15 report noted that 'pporappippam' reached the Circle Digital Chart top 10 in 2020 and identified 'Heart Burn' as another seasonal hit in 2022. Both songs favored mood over a crowded beach-party formula. 'Forever July' pushes that distinction further by making unstable weather the central image.",
      "The cultural value sits in that weather. Korea's rainy season changes commutes, clothing, street light and the pace of daily life. Pop often turns summer into a universal postcard of blue sky and escape. Sunmi keeps the season local and unsettled. The damp visual world also gives the song an emotional language for attraction that feels exciting and difficult at once. The artistic wager is that this specificity will make the record easier to recognize across borders by giving listeners a complete point of view.",
      "The strongest counterargument is simple. Summer listeners may want release from humidity instead of a reminder of it. A digital single also lacks the physical-sales engine, collectible versions and concentrated fandom purchases that support many current K-pop chart debuts. A strong concept can earn attention on release day, while durable demand still depends on repeated listening after the visual campaign slows.",
      "Sunmi's career stage makes that risk useful. She has less reason to imitate the release volume of younger groups. A seasonal record that carries her writing and composing credits can deepen a recognizable catalogue and return every July if the public adopts it. That recurring value matters more than one crowded week of promotional clips. The strategy works when authorship, image and listening occasion reinforce one another, as they do here.",
      "Circle Digital Chart results provide the checkpoint. The bullish call holds if 'Forever July' reaches the top 30 by the chart week ending August 15, 2026, and remains in the top 100 for the week ending September 5. Missing both marks would show that the monsoon concept created a memorable campaign without creating a durable summer song.",
    ],
    source: SUNMI_FOREVER_JULY,
    related: {},
  },
  {
    slug: "yg-concert-accessibility-standard",
    title: "YG's accessibility work can reset the concert standard",
    dek: "Captioning, sensory bags and trained support staff move inclusion into concert operations. Measurable coverage across every Korean show is the next test.",
    status: "analysis",
    pillar: "k-pop",
    author: "MyKStars",
    date: "2026-07-16T13:00:00+09:00",
    body: [
      "YG Entertainment's concert accessibility program can reset the concert standard in Korea. Its *2026 Sustainable Concert Report* treats captions, navigation, sensory support and staff training as production work. The bullish call depends on repeatable coverage beyond selected pilots.",
      "The report, dated May 2026, describes an independent review at AKMU's 10th-anniversary 10VE concert in June 2024. Six people with disabilities assessed the journey from ticket booking through the end of the show. They found gaps in screen-reader support, alternative text, keyboard navigation and accessibility inquiry channels. They also sought clear venue information on drop-off zones, accessible routes, elevators, braille and large-print materials, and evacuation procedures.",
      "YG changed the journey. It added pre-concert information for visually impaired users, a way to request accessibility staff and links in booking confirmation messages. It trained support staff and expanded accessibility maps. Real-time captioning was offered at 10VE. Sensory bags were introduced for sensory-sensitive guests at BLACKPINK WORLD TOUR DEADLINE IN GOYANG in July 2025. YG's 2024 sustainability report also said more than 80.9 percent of surveyed fans rated BLACKPINK's Seoul accessibility guide video positively.",
      "Those details matter because concert culture often asks fans to prove devotion through endurance. Long queues, dense crowds, bright light, loud sound and unfamiliar routes can turn participation into a physical test. Accessible information gives people more control before they arrive. Captions and sensory support widen the meaning of a shared performance once the show begins. A concert becomes culturally larger when more people can enter it on equal terms.",
      "The strongest counterargument is the evidence base. YG reports its own work and highlights a small number of shows. The documents do not state how many guests used each service, what share of concerts received the full package, how many accessible seats were available or how accessibility complaints were resolved. A well-made guide at one flagship event does not establish an agency-wide standard. The current record shows serious design work and incomplete accountability.",
      "The mechanism for scale is operational. An agency can place accessibility requirements in venue contracts, production checklists, ticketing pages and tour briefs. That makes support less dependent on one artist or one local promoter. It also gives vendors a stable specification they can improve. YG has already connected user testing to concrete changes, which is the hardest part of the cycle to begin.",
      "YG's published roadmap sets the checkpoint. Its 2024 roadmap set a 2027 milestone for all concerts in Korea and selected overseas shows. The 2026 report says the framework should cover every YG concert in Korea and abroad by 2030. The next report, assessed by June 30, 2027, should disclose a concert-by-concert coverage table with services, gaps and usage measures. This bullish call holds if the table shows that every Korean YG show staged in the first half of 2027 delivered accessible booking information, trained support, route guides, captioning and sensory support. Another report built only around selected examples would overturn it.",
    ],
    source: YG_CONCERT_ACCESSIBILITY,
    related: { artistSlugs: ["blackpink"] },
  },
  {
    slug: "webtoon-tv-creator-transparency",
    title: "Webtoon television wins are outrunning creator transparency",
    dek: "*Agent Kim Reactivated* and *Teach You a Lesson* became global television hits. Industry reporting still says too little about how adaptation value reaches original creators.",
    status: "analysis",
    pillar: "k-drama",
    author: "MyKStars",
    date: "2026-07-16T11:30:00+09:00",
    body: [
      "Korean webtoons have become television's most efficient story laboratory. Creator participation reporting trails their adaptation value. The bearish call is that another year of global screen hits will deepen a specific transparency gap unless official statistics isolate creators' adaptation income and continuing financial participation.",
      "Netflix reported that *Agent Kim Reactivated*, adapted from *Manager Kim*, led its non-English television list with 10.5 million views for June 29 through July 5, 2026. On June 17, Netflix said *Teach You a Lesson*, another webtoon adaptation, recorded 21.1 million views in one week. It ranked first in 46 countries and reached the top 10 in 91. Both arrived with proven characters, visual grammar and ready audiences.",
      "KOCCA's public edition of the *2025 Webtoon Industry Survey*, registered January 2, 2026, put 2024 industry revenue at KRW 2.286 trillion and reported a 4.4 percent increase. Japan accounted for 49.5 percent of exports and North America for 21.0 percent. The report found a KRW 42 million median annual income among creators who serialized throughout 2024, averages of 9.4 hours per creative day and 5.8 creative days weekly. KOCCA warned that new industry methods and a changed creator sample limit comparisons with earlier surveys.",
      "The screen pipeline explains the business appeal. A serialized webtoon tests characters and pacing in public before a producer commits a television budget. Panels already provide a visual development record. Episode endings supply a map for streaming structure. Existing readership lowers the cost of explaining a new title. Each hit can also send viewers back to the original work and open games, merchandise or foreign remake rights.",
      "The strongest counterargument is that the new survey already gives useful contract visibility. Among businesses that secured secondary-work rights during serialization agreements, 57.9 percent used a license, 17.8 percent a transfer and 9.2 percent shared rights. Private deal-level disclosure could weaken negotiations or expose personal income. Anonymized reporting protects that information. The remaining gap is narrower: public tables show how businesses secure secondary rights and what legal forms they use, while creator-level adaptation income and continuing financial participation stay unmeasured.",
      "This is also a cultural question. Webtoon artists and writers build stories inside a distinctly Korean digital reading form, then television carries those stories worldwide. Clear credit is essential, and visible economic participation gives creators time to make the next work. An adaptation system that celebrates the screen result while leaving the originating labor statistically invisible weakens its own supply of ideas.",
      "KOCCA's next annual survey is the checkpoint. By December 31, 2026, it should isolate creator income from screen adaptations and other secondary rights, plus the share of screen deals that provide continuing financial participation. This bearish call is overturned if the report publishes both creator-level measures, defines its sample and separates television, film, games and merchandise. A survey that repeats only business-side rights structures would leave the success story incomplete.",
    ],
    source: KOCCA_2025_WEBTOON_SURVEY,
    related: {},
  },
  {
    slug: "korean-cinema-southeast-asia-local-leadership",
    title: "Korean cinema grows abroad when local creators lead",
    dek: "*Mansion of Mr. Hua* topped Vietnam's box office with a Vietnamese creative team and Korean financing support. Shared production offers a durable export model.",
    status: "analysis",
    pillar: "k-movie",
    author: "MyKStars",
    date: "2026-07-16T10:00:00+09:00",
    body: [
      "Korean cinema's strongest route into Southeast Asia places local creators in charge of the story and uses Korean expertise as supporting infrastructure. The June success of *Mansion of Mr. Hua* makes that a bullish industry call. Shared development and ownership can travel further than a Korean format transplanted into another culture.",
      "KOFIC's *Korean Film* magazine reported on July 13, 2026, that *Mansion of Mr. Hua* reached No. 1 at the Vietnamese box office six days after release. Runup Vietnam and Korea's Hive Media Corp. co-produced the found-footage horror film. Vietnamese filmmakers led story development, production, direction, acting and marketing. Hive Media supplied planning experience, production support and financing. The film drew its premise from a real Ho Chi Minh City mansion and local ghost stories.",
      "That division of work is the important result. Korean participation did not require visible Korean characters or a borrowed Korean plot. Local knowledge shaped the fear, space and folklore on screen. Korean capital and production systems helped the project reach market scale. The partnership therefore expanded what Korean cinema can do abroad while preserving the cultural authority of the people closest to the material.",
      "A second model is forming in Indonesia. KOFIC cited *Ghost in the Cell*, co-produced by Korea's Barunson E&A and Indonesian director Joko Anwar's Come and See Pictures. Barunson also handled international sales. The film drew 3.36 million admissions in Indonesia and premiered at the 2026 Berlin International Film Festival. Both cases treat relationships and skills as the export, with the finished film rooted in its own culture.",
      "The strongest counterargument concerns power. Financing, sales access and intellectual-property contracts can still give the Korean partner more control than the credits suggest. A locally cast film can reproduce extraction behind the camera. Fast expansion can also flatten distinct Southeast Asian cultures into one market category. The article's own evidence is early: one Vietnamese box-office leader and one Indonesian festival selection do not yet prove a durable regional system.",
      "KOFIC's policy response creates a measurable next step. Its 2026 International Co-production Pilot Program offers up to KRW 500 million per selected project. The first-half call drew 19 applications, including 11 involving Southeast Asian partners. KOFIC also plans a development-support program for 2027. Public funding should require clear creative leadership, shared rights and transparent local spending. Those terms would make cultural respect part of the production structure.",
      "Results through June 30, 2027, provide the checkpoint. The bullish call holds if at least two pilot-backed Southeast Asian co-productions reach production with local writers and directors, disclosed shared-IP terms, and either a top-five local box-office finish or official selection at Berlin, Cannes or Venice. If the program mainly finances Korean remakes or leaves ownership undisclosed, *Mansion of Mr. Hua* will look like an exception instead of a new model.",
    ],
    source: KOFIC_SOUTHEAST_ASIA_STRATEGY,
    related: {},
  },
  // --- 2026-07-15 Analysis run: two artist calls, one company and one industry flagship ---
  {
    slug: "katseye-wild-catalogue-win",
    title: "KATSEYE can turn *WILD* into a catalogue win",
    dek: "*BEAUTIFUL CHAOS* paired a No. 4 opening with 19 weeks of chart life. Three AMA wins and a 31-date arena sellout give the follow-up room to raise both the debut and the hold.",
    status: "analysis",
    pillar: "k-pop",
    author: "MyKStars",
    date: "2026-07-15T13:30:00+09:00",
    body: [
      "*BEAUTIFUL CHAOS* already paired a No. 4 opening with 19 weeks of chart life. Three American Music Award wins and a 31-date arena sellout give *WILD* enough expanded demand to raise both the debut and the hold.",
      "*Billboard Brasil* reported on July 6, 2025, that *BEAUTIFUL CHAOS* opened with 44,000 album-equivalent units: 30,000 album sales and 14,000 streaming-equivalent units from 21.36 million on-demand streams. *Billboard Japan* then recorded the EP at No. 43 in its nineteenth Billboard 200 week on the chart dated November 15, 2025. KATSEYE has already shown that its audience can keep listening after release week.",
      "The campaign is larger now. Universal Music Japan reported on May 27, 2026, that KATSEYE won all three of its nominated American Music Award categories and sold out all 31 dates of THE WILDWORLD TOUR in under 48 hours. Awards and arena sales measure attention and live demand, while preorder incentives can still concentrate album consumption in week one.",
      "The bullish call requires two results. *WILD* must open with at least 60,000 units and a top three rank on the Billboard 200 dated August 29, then remain in the top 50 in week four on September 19.",
    ],
    source: KATSEYE_WILD_CAMPAIGN,
    related: { artistSlugs: ["katseye"] },
  },
  {
    slug: "ateez-number-one-listening-test",
    title: "ATEEZ has mastered the No. 1 debut. The next test is listening",
    dek: "*GOLDEN HOUR : Part.5* set a career peak through sales, then fell to No. 19 in week two. Recurring US listening now carries the growth test.",
    status: "analysis",
    pillar: "k-pop",
    author: "MyKStars",
    date: "2026-07-15T12:00:00+09:00",
    body: [
      "*GOLDEN HOUR : Part.5* converted ATEEZ's collector base into a record Billboard 200 No. 1, but a 97.8 percent sales share and a fall from No. 1 to No. 19 in week two leave the group's next US growth test in recurring listening.",
      "On July 6, 2026, *Billboard Japan* reported 228,000 album-equivalent units for the chart dated July 11: 223,000 traditional sales and 5,000 streaming-equivalent units from 4.96 million on-demand streams. Yonhap reported on July 3 that Hanteo first-week sales exceeded 1.88 million, another group record.",
      "The strongest opposing case is durable demand. ATEEZ has nine Billboard 200 top 10 releases, while *GOLDEN HOUR : Part.5* remained No. 1 on World Albums and No. 2 on Top Album Sales in its second week, according to the July 15 *Star News* chart report. Those results confirm repeat purchasing strength. Multiweek Billboard 200 retention offers the clearer test of listening beyond the collector base.",
      "The checkpoint is the Billboard 200 dated September 12, the EP's tenth chart week. A top 100 rank overturns this bearish call. A position below No. 100, or an earlier exit, supports it.",
    ],
    source: ATEEZ_BILLBOARD_WEEK_TWO,
    related: { artistSlugs: ["ateez"] },
  },
  {
    slug: "jyp-tour-shop-release-calendar",
    title: "JYP's tour shops are becoming a second release calendar",
    dek: "Q1 revenue rose 32.1 percent without a major artist album. The next quarter will show whether tour-linked city shops can keep Blue Garage above a double-digit margin.",
    status: "analysis",
    pillar: "k-pop",
    author: "MyKStars",
    date: "2026-07-15T10:30:00+09:00",
    body: [
      "JYP Entertainment's first quarter shows that tour-linked city popups can create a profitable sales calendar between major-artist albums. The bullish call is that Blue Garage can keep double-digit margins after delayed online-order recognition rolls off.",
      "JYP's FY26 Q1 Earnings Note, published May 15, 2026, recorded KRW 186.0 billion in consolidated revenue, up 32.1 percent from the prior-year quarter. Operating profit reached KRW 33.4 billion, up 70.0 percent, for a 17.9 percent operating margin. The quarter carried no major-artist album, and physical-recording revenue fell 15.1 percent to KRW 25.2 billion.",
      "Touring commerce filled that gap. Merchandise revenue reached KRW 60.6 billion, up 85.2 percent, while concert revenue reached KRW 40.9 billion, up 88.7 percent. Together they supplied KRW 101.5 billion, or 54.6 percent of consolidated revenue. Blue Garage raised revenue 180.5 percent to KRW 40.9 billion and posted an 11.1 percent operating margin. JYP mapped TWICE-linked popups across five cities in late 2025 and seven in Q1, with nine more planned for Q2.",
      "That cadence gives one tour several local sales windows and spreads product drops across months. It also makes touring a second release calendar, with merchandise tied to a live event rather than one album week. The model can keep intellectual property earning while the recording slate is light, and Q1 shows that fans will follow the schedule across markets.",
      "The strongest counterargument sits in recognition timing and artist concentration. JYP said part of Q1 Blue Garage revenue came from online deliveries completed after Stray Kids' October 2025 encore and TWICE's tenth-anniversary popup. Its November 14, 2025, FY25 Q3 Earnings Note also recorded a 20.5 percent merchandise decline to KRW 40.0 billion when large project sales were absent. Blue Garage's cumulative operating margin then sat near 9 percent. Those figures expose the volatility behind a quarter led by TWICE and Stray Kids.",
      "JYP's FY26 Q2 Earnings Note, assessed by August 31, 2026, is the checkpoint. The bullish call holds if at least two of three marks are met: merchandise revenue of KRW 50 billion or more, a Blue Garage operating margin of at least 10 percent, and a consolidated operating margin of at least 17 percent. The nine planned Q2 popup cities make that report the direct test of repeatability.",
    ],
    source: JYP_FY26_Q1,
    related: { artistSlugs: ["twice", "stray-kids", "nmixx"] },
  },
  {
    slug: "korean-cinema-distributor-concentration",
    title: "Korean cinema's record quarter belongs to one distributor",
    dek: "Admissions reached a post-2020 Q1 high, while Showbox captured 55.4 percent of revenue. Its hold on 2026's three biggest Korean releases keeps the recovery concentrated.",
    status: "analysis",
    pillar: "k-movie",
    author: "MyKStars",
    date: "2026-07-15T09:00:00+09:00",
    body: [
      "Korean theatrical demand has rebounded, but Showbox's control of the three biggest 2026 Korean releases means the recovery is still a distributor concentration story rather than a broad market recovery.",
      "The Korean Film Council's annual report, published February 27, 2026, put 2025 box-office revenue at KRW 1.047 trillion and admissions at 106.09 million. Revenue fell 12.4 percent from 2024, while admissions fell 13.8 percent. That weak base made the first-quarter rebound welcome and left breadth as the harder test.",
      "KOFIC's April 29 report recorded KRW 318.0 billion in first-quarter revenue and 31.9 million admissions, the strongest Q1 results since 2020. Korean films captured 73.4 percent of revenue. Showbox releases generated KRW 176.3 billion, equal to 55.4 percent of the entire market, while second-place Disney Korea took KRW 43.1 billion and 13.6 percent. Audience demand returned around a concentrated slate.",
      "The live KOBIS yearly table on July 15 places *The King's Warden*, *Colony* and *Salmokji* as the three leading 2026 Korean releases, with 16.91 million, 5.90 million and 3.24 million admissions. Showbox distributed all three. The run gives the recovery real force, while one distributor's command of the largest titles leaves rival pipelines with little evidence of comparable scale.",
      "The strongest counterargument is the range inside Showbox's run. Romance, historical drama, horror and zombie action have all found audiences, which points to demand across genres rather than a single-film anomaly. Genre breadth within one distributor still leaves financing and distribution breadth narrow. A durable national recovery needs multiple companies to turn multiple films into events.",
      "KOBIS results through August 31, 2026, provide the checkpoint. This bearish call is overturned only if at least two of the five highest-grossing Korean films released in 2026 come from non-Showbox distributors and each exceeds three million admissions. Any result below that mark supports the concentration thesis.",
    ],
    source: KOBIS_2026_YEARLY,
    related: {},
  },
  // --- 2026-07-05 roster expansion: multi-artist analysis for the new subjects ---
  {
    slug: "arirang-numbers-reading",
    title: "Reading the *Arirang* return: what the numbers actually say",
    dek: "A No. 1 debut, a free show at Gwanghwamun, a sold-out stadium run: BTS's comeback is best understood as three different records at once.",
    status: "analysis",
    pillar: "k-pop",
    author: "MyKStars",
    date: "2026-07-03T09:00:00+09:00",
    body: [
      "Comebacks after a service gap usually restart an engine. *Arirang* skipped the warmup: a Billboard 200 No. 1, the biggest Korean first week of the year, and a tour that sold through its London, Paris and Los Angeles stadium legs before the first night.",
      "The subtler number is the free one. The Gwanghwamun show in March cost nothing to attend and worked as a statement of scale: the group's first full stage in nearly four years, held as a public event in the middle of Seoul rather than behind a paywall.",
      "What to watch next is durability: whether the album's tracks re-enter the global charts as the European and American legs roll through the summer. That is the version of momentum that outlives a release week.",
    ],
    source: NEWS1,
    related: { artistSlugs: ["bts"], gallerySlugs: ["bts-gwanghwamun-comeback", "bts-the-city-london"] },
  },
  {
    slug: "rookie-class-2026-first-week-curve",
    title: "The 2026 rookie class is bending the first-week curve",
    dek: "CORTIS and Hearts2Hearts turned respectable debuts into record sophomore weeks. The old rookie math no longer holds.",
    status: "analysis",
    pillar: "k-pop",
    author: "MyKStars",
    date: "2026-07-02T09:00:00+09:00",
    body: [
      "For years the informal bar for a strong rookie debut sat around two hundred thousand first-week copies. The 2026 class made that a floor, not a ceiling: CORTIS moved over 2.3 million copies of *GREENGREEN* in a week, and Hearts2Hearts set a personal best just short of six hundred thousand with *Lemon Tang*.",
      "The pattern is the same in both cases: a solid debut, then a sophomore release that scales five to ten times. The machinery behind it (global pre-saves, day-one tour announcements, festival slots booked before the first anniversary) compresses what used to be a three-year build into eighteen months.",
      "The question that matters for the rest of the year is whether the third release holds the altitude. That, more than any award, is what separates a class from a cohort.",
    ],
    source: STAR_NEWS,
    related: {
      artistSlugs: ["cortis", "hearts2hearts", "babymonster"],
      gallerySlugs: ["cortis-golden-disc-rookie", "hearts2hearts-lemon-tang-week"],
    },
  },
  {
    slug: "girl-group-brand-race-2026",
    title: "The mid-2026 girl group brand race, in three moves",
    dek: "IVE hold the top, BLACKPINK surge on the *Deadline* era, and LE SSERAFIM turn a Macarena sample into a tour setup.",
    status: "analysis",
    pillar: "k-pop",
    author: "MyKStars",
    date: "2026-06-30T09:00:00+09:00",
    body: [
      "Brand reputation indexes are a blunt instrument, but they move on real events. IVE's hold on first place tracks a comeback cycle that never quite cooled; BLACKPINK's climb follows the *Deadline* records; LE SSERAFIM's rise maps almost exactly onto the week 'BOOMPALA' landed.",
      "What the index cannot see is the touring map underneath it. All three acts spend the second half of 2026 on the road, which means the next six months of this race will be decided in arenas, not on release calendars.",
    ],
    source: STAR_NEWS,
    related: {
      artistSlugs: ["ive", "blackpink", "le-sserafim"],
      gallerySlugs: ["ive-blackhole-comeback", "le-sserafim-boompala-comeback"],
    },
  },
  {
    slug: "monochrome-concept-photos-2026",
    title: "Why monochrome concept photos are dominating 2026 comebacks",
    dek: "Black-and-white sets read as 'premium' and travel well across platforms. A look at why agencies keep reaching for them.",
    status: "analysis",
    pillar: "k-pop",
    author: "MyKStars",
    date: "2026-06-21T13:00:00+09:00",
    body: [
      "Strip the color out of a concept set and two things happen at once: the styling reads as more expensive, and the images survive the journey through dozens of feeds, reposts and compression passes without falling apart. That durability matters when a comeback lives or dies in the first six hours of sharing.",
      "Monochrome also sidesteps the seasonal-palette problem. A set shot in black and white doesn't date the way a hyper-specific color story does, which is useful when the same images will anchor an artist hub for months.",
      "The risk is sameness. When everyone reaches for the same restraint, the differentiation moves back to where it always lived: styling, casting of the photographer, and the strength of a single hero frame.",
    ],
    source: NEWSEN,
    related: { artistSlugs: ["newjeans", "stray-kids"] },
  },
  {
    slug: "the-airport-runway",
    title: "The airport runway: how a 5 a.m. departure became fashion theater",
    dek: "Incheon's press line is now a styled event in its own right. We trace how 'airport fashion' became a genre.",
    status: "analysis",
    pillar: "k-pop",
    author: "MyKStars",
    date: "2026-06-21T10:30:00+09:00",
    body: [
      "There is nothing accidental about an airport look. Outfits are planned, sometimes pulled from a brand the artist represents, and timed to a press line that everyone in the room knows is coming.",
      "For global fans, the airport set is often the first high-resolution sighting of an artist between official schedules, which is exactly why organized, credited airport galleries are one of the most-searched things in the fandom and one of the least well served in English.",
    ],
    source: OSEN,
    related: { artistSlugs: ["blackpink", "twice"], gallerySlugs: ["blackpink-incheon-airport"] },
  },
  {
    slug: "kdrama-global-default",
    title: "How global streaming made K-drama a default, not a niche",
    dek: "Korean series are now a standing fixture on the world's streaming charts. We look at what that changes for how they're covered.",
    status: "analysis",
    pillar: "k-drama",
    author: "MyKStars",
    date: "2026-06-21T08:00:00+09:00",
    body: [
      "A decade ago, finding a Korean drama with reliable English subtitles took effort. Now a new title can open simultaneously in dozens of countries and sit on a global top-ten chart by the weekend. The discovery problem has inverted from scarcity to overload.",
      "That shift moves the coverage gap. The audience no longer needs to be told a show exists; it needs help deciding what to start, where to watch it without hunting across four services, and who is in it. Organized, credited stills and a clear where-to-watch line do more work than a recap ever did.",
    ],
    source: STUDIO,
    related: { artistSlugs: ["kim-tae-ri", "park-eun-bin"], gallerySlugs: ["drama-production-presentation"] },
  },
  {
    slug: "casting-season",
    title: "Casting season: how to read the tea leaves of a lineup",
    dek: "A casting announcement is the first marketing beat of a drama. Here's what the portrait drop is really telling you.",
    status: "analysis",
    pillar: "k-drama",
    author: "MyKStars",
    date: "2026-06-20T12:00:00+09:00",
    body: [
      "The character-portrait drop that accompanies a casting confirmation is a genre of its own: styled, lit, and released on a schedule designed to seed months of anticipation before a single scene airs.",
      "Read the lineup and you can usually read the budget, the target audience, and the tone. A cross-pillar cast (an idol stepping into a lead, a film actor taking a television role) is its own signal, and one worth following across the rest of the site.",
    ],
    source: STUDIO,
    related: { artistSlugs: ["lee-min-ho", "park-eun-bin"], gallerySlugs: ["drama-casting-ensemble"] },
  },
  {
    slug: "idol-ambassador-economy",
    title: "The idol-as-ambassador economy",
    dek: "Pictorials and house campaigns have become many artists' main visual output between comebacks. A look at the loop.",
    status: "analysis",
    pillar: "fashion-beauty",
    author: "MyKStars",
    date: "2026-06-21T07:00:00+09:00",
    body: [
      "Between comebacks, the steady drumbeat of an artist's visual presence is increasingly fashion and beauty work: a magazine cover, a house campaign, a front-row appearance. For a photo-first publication, that work is a pillar of K-pop coverage in its own right.",
      "The mechanics are a loop. A campaign produces editorial imagery; the imagery travels through fan accounts; the reach justifies the next ambassadorship. Crediting the photographer, stylist and glam team is the part of the story everyone else leaves out, and we treat that credit line as reporting.",
    ],
    source: VOGUE_KOREA,
    related: { artistSlugs: ["jung-hoyeon", "cha-eunwoo"], gallerySlugs: ["vogue-korea-editorial"] },
  },
  {
    slug: "festival-circuit-explained",
    title: "The festival circuit, explained",
    dek: "Busan, Cannes, Berlin: why the photocall still matters in a streaming-first world, and what it signals for Korean film.",
    status: "analysis",
    pillar: "k-movie",
    author: "MyKStars",
    date: "2026-06-20T19:00:00+09:00",
    body: [
      "Theatrical admissions have softened, but the festival photocall has, if anything, grown in importance: it's the moment a film's images enter the global conversation, and where a director's standing is publicly recognized.",
      "For Korean cinema specifically, the circuit is a prestige engine that feeds back into everything else: the auteur whose film premieres at Busan is the same name a drama production wants attached, and the same face a fashion house wants in the front row.",
    ],
    source: FESTIVAL,
    related: { artistSlugs: ["park-chan-wook", "bong-joon-ho"], gallerySlugs: ["busan-opening-photocall"] },
  },
  {
    slug: "what-confirmed-means",
    title: "Confirmed: what this label means on MyKStars",
    dek: "We attach 'Confirmed' only to facts an official source has stated on the record, and we link that source every time.",
    status: "confirmed",
    author: "MyKStars",
    date: "2026-06-20T17:00:00+09:00",
    body: [
      "A 'Confirmed' label is a promise, not a flourish. We apply it only when a primary source (an agency notice, an official account, a venue, or the artist) has stated something on the record, and we link directly to that source so you can check it yourself.",
      "If a detail is reported by other outlets but not confirmed at the source, it does not get this label. That discipline is the whole point: the label has to mean something for it to be worth showing.",
    ],
    related: {},
  },
  {
    slug: "how-we-handle-rumors",
    title: "Unverified: a report is circulating, and here's what we will and won't publish",
    dek: "When an unconfirmed personal claim spreads, our default is restraint. We explain the standard rather than amplify the rumor.",
    status: "unverified",
    author: "MyKStars",
    date: "2026-06-20T16:00:00+09:00",
    body: [
      "Unverified reports, especially about anyone's private life, travel faster than the facts behind them. Our policy is simple: we do not repeat an unconfirmed personal claim as if it were established, and we never build a gallery whose only purpose is to capitalize on one.",
      "When something is genuinely newsworthy but unconfirmed, we say plainly what is known, what is not, and who would have to confirm it for the story to change. The 'Unverified' label exists so that status is never ambiguous.",
    ],
    related: {},
  },
];
