import type { Article } from "@/lib/types";
import { FESTIVAL, NEWS1, NEWSEN, OSEN, STAR_NEWS, STUDIO, VOGUE_KOREA } from "./sources";

// ---------------------------------------------------------------------------
// ARTICLES
// ---------------------------------------------------------------------------
export const articles: Article[] = [
  // --- 2026-07-05 roster expansion: multi-artist analysis for the new subjects ---
  {
    slug: "arirang-numbers-reading",
    title: "Reading the *Arirang* return: what the numbers actually say",
    dek: "A No. 1 debut, a free show at Gwanghwamun, a sold-out stadium run: BTS's comeback is best understood as three different records at once.",
    status: "analysis",
    pillar: "k-pop",
    author: "MyKStars",
    date: "2026-07-03T09:00:00+09:00",
    body: [
      "Comebacks after a service gap usually restart an engine. *Arirang* skipped the warmup: a Billboard 200 No. 1, the biggest Korean first week of the year, and a tour that sold through its London, Paris and Los Angeles stadium legs before the first night.",
      "The subtler number is the free one. The Gwanghwamun show in March cost nothing to attend and worked as a statement of scale: the group's first full stage in nearly four years, held as a public event in the middle of Seoul rather than behind a paywall.",
      "What to watch next is durability: whether the album's tracks re-enter the global charts as the European and American legs roll through the summer. That is the version of momentum that outlives a release week.",
    ],
    source: NEWS1,
    related: { artistSlugs: ["bts"], gallerySlugs: ["bts-gwanghwamun-comeback", "bts-the-city-london"] },
  },
  {
    slug: "rookie-class-2026-first-week-curve",
    title: "The 2026 rookie class is bending the first-week curve",
    dek: "CORTIS and Hearts2Hearts turned respectable debuts into record sophomore weeks. The old rookie math no longer holds.",
    status: "analysis",
    pillar: "k-pop",
    author: "MyKStars",
    date: "2026-07-02T09:00:00+09:00",
    body: [
      "For years the informal bar for a strong rookie debut sat around two hundred thousand first-week copies. The 2026 class made that a floor, not a ceiling: CORTIS moved over 2.3 million copies of *GREENGREEN* in a week, and Hearts2Hearts set a personal best just short of six hundred thousand with *Lemon Tang*.",
      "The pattern is the same in both cases: a solid debut, then a sophomore release that scales five to ten times. The machinery behind it (global pre-saves, day-one tour announcements, festival slots booked before the first anniversary) compresses what used to be a three-year build into eighteen months.",
      "The question that matters for the rest of the year is whether the third release holds the altitude. That, more than any award, is what separates a class from a cohort.",
    ],
    source: STAR_NEWS,
    related: {
      artistSlugs: ["cortis", "hearts2hearts", "babymonster"],
      gallerySlugs: ["cortis-golden-disc-rookie", "hearts2hearts-lemon-tang-week"],
    },
  },
  {
    slug: "girl-group-brand-race-2026",
    title: "The mid-2026 girl group brand race, in three moves",
    dek: "IVE hold the top, BLACKPINK surge on the *Deadline* era, and LE SSERAFIM turn a Macarena sample into a tour setup.",
    status: "analysis",
    pillar: "k-pop",
    author: "MyKStars",
    date: "2026-06-30T09:00:00+09:00",
    body: [
      "Brand reputation indexes are a blunt instrument, but they move on real events. IVE's hold on first place tracks a comeback cycle that never quite cooled; BLACKPINK's climb follows the *Deadline* records; LE SSERAFIM's rise maps almost exactly onto the week 'BOOMPALA' landed.",
      "What the index cannot see is the touring map underneath it. All three acts spend the second half of 2026 on the road, which means the next six months of this race will be decided in arenas, not on release calendars.",
    ],
    source: STAR_NEWS,
    related: {
      artistSlugs: ["ive", "blackpink", "le-sserafim"],
      gallerySlugs: ["ive-blackhole-comeback", "le-sserafim-boompala-comeback"],
    },
  },
  {
    slug: "monochrome-concept-photos-2026",
    title: "Why monochrome concept photos are dominating 2026 comebacks",
    dek: "Black-and-white sets read as 'premium' and travel well across platforms. A look at why agencies keep reaching for them.",
    status: "analysis",
    pillar: "k-pop",
    author: "MyKStars",
    date: "2026-06-21T13:00:00+09:00",
    body: [
      "Strip the color out of a concept set and two things happen at once: the styling reads as more expensive, and the images survive the journey through dozens of feeds, reposts and compression passes without falling apart. That durability matters when a comeback lives or dies in the first six hours of sharing.",
      "Monochrome also sidesteps the seasonal-palette problem. A set shot in black and white doesn't date the way a hyper-specific color story does, which is useful when the same images will anchor an artist hub for months.",
      "The risk is sameness. When everyone reaches for the same restraint, the differentiation moves back to where it always lived: styling, casting of the photographer, and the strength of a single hero frame.",
    ],
    source: NEWSEN,
    related: { artistSlugs: ["newjeans", "stray-kids"] },
  },
  {
    slug: "the-airport-runway",
    title: "The airport runway: how a 5 a.m. departure became fashion theater",
    dek: "Incheon's press line is now a styled event in its own right. We trace how 'airport fashion' became a genre.",
    status: "analysis",
    pillar: "k-pop",
    author: "MyKStars",
    date: "2026-06-21T10:30:00+09:00",
    body: [
      "There is nothing accidental about an airport look. Outfits are planned, sometimes pulled from a brand the artist represents, and timed to a press line that everyone in the room knows is coming.",
      "For global fans, the airport set is often the first high-resolution sighting of an artist between official schedules, which is exactly why organized, credited airport galleries are one of the most-searched things in the fandom and one of the least well served in English.",
    ],
    source: OSEN,
    related: { artistSlugs: ["blackpink", "twice"], gallerySlugs: ["blackpink-incheon-airport"] },
  },
  {
    slug: "kdrama-global-default",
    title: "How global streaming made K-drama a default, not a niche",
    dek: "Korean series are now a standing fixture on the world's streaming charts. We look at what that changes for how they're covered.",
    status: "analysis",
    pillar: "k-drama",
    author: "MyKStars",
    date: "2026-06-21T08:00:00+09:00",
    body: [
      "A decade ago, finding a Korean drama with reliable English subtitles took effort. Now a new title can open simultaneously in dozens of countries and sit on a global top-ten chart by the weekend. The discovery problem has inverted from scarcity to overload.",
      "That shift moves the coverage gap. The audience no longer needs to be told a show exists; it needs help deciding what to start, where to watch it without hunting across four services, and who is in it. Organized, credited stills and a clear where-to-watch line do more work than a recap ever did.",
    ],
    source: STUDIO,
    related: { artistSlugs: ["kim-tae-ri", "park-eun-bin"], gallerySlugs: ["drama-production-presentation"] },
  },
  {
    slug: "casting-season",
    title: "Casting season: how to read the tea leaves of a lineup",
    dek: "A casting announcement is the first marketing beat of a drama. Here's what the portrait drop is really telling you.",
    status: "analysis",
    pillar: "k-drama",
    author: "MyKStars",
    date: "2026-06-20T12:00:00+09:00",
    body: [
      "The character-portrait drop that accompanies a casting confirmation is a genre of its own: styled, lit, and released on a schedule designed to seed months of anticipation before a single scene airs.",
      "Read the lineup and you can usually read the budget, the target audience, and the tone. A cross-pillar cast (an idol stepping into a lead, a film actor taking a television role) is its own signal, and one worth following across the rest of the site.",
    ],
    source: STUDIO,
    related: { artistSlugs: ["lee-min-ho", "park-eun-bin"], gallerySlugs: ["drama-casting-ensemble"] },
  },
  {
    slug: "idol-ambassador-economy",
    title: "The idol-as-ambassador economy",
    dek: "Pictorials and house campaigns have become many artists' main visual output between comebacks. A look at the loop.",
    status: "analysis",
    pillar: "fashion-beauty",
    author: "MyKStars",
    date: "2026-06-21T07:00:00+09:00",
    body: [
      "Between comebacks, the steady drumbeat of an artist's visual presence is increasingly fashion and beauty work: a magazine cover, a house campaign, a front-row appearance. For a photo-first publication, that work is a pillar of K-pop coverage in its own right.",
      "The mechanics are a loop. A campaign produces editorial imagery; the imagery travels through fan accounts; the reach justifies the next ambassadorship. Crediting the photographer, stylist and glam team is the part of the story everyone else leaves out, and we treat that credit line as reporting.",
    ],
    source: VOGUE_KOREA,
    related: { artistSlugs: ["jung-hoyeon", "cha-eunwoo"], gallerySlugs: ["vogue-korea-editorial"] },
  },
  {
    slug: "festival-circuit-explained",
    title: "The festival circuit, explained",
    dek: "Busan, Cannes, Berlin: why the photocall still matters in a streaming-first world, and what it signals for Korean film.",
    status: "analysis",
    pillar: "k-movie",
    author: "MyKStars",
    date: "2026-06-20T19:00:00+09:00",
    body: [
      "Theatrical admissions have softened, but the festival photocall has, if anything, grown in importance: it's the moment a film's images enter the global conversation, and where a director's standing is publicly recognized.",
      "For Korean cinema specifically, the circuit is a prestige engine that feeds back into everything else: the auteur whose film premieres at Busan is the same name a drama production wants attached, and the same face a fashion house wants in the front row.",
    ],
    source: FESTIVAL,
    related: { artistSlugs: ["park-chan-wook", "bong-joon-ho"], gallerySlugs: ["busan-opening-photocall"] },
  },
  {
    slug: "what-confirmed-means",
    title: "Confirmed: what this label means on MyKStars",
    dek: "We attach 'Confirmed' only to facts an official source has stated on the record, and we link that source every time.",
    status: "confirmed",
    author: "MyKStars",
    date: "2026-06-20T17:00:00+09:00",
    body: [
      "A 'Confirmed' label is a promise, not a flourish. We apply it only when a primary source (an agency notice, an official account, a venue, or the artist) has stated something on the record, and we link directly to that source so you can check it yourself.",
      "If a detail is reported by other outlets but not confirmed at the source, it does not get this label. That discipline is the whole point: the label has to mean something for it to be worth showing.",
    ],
    related: {},
  },
  {
    slug: "how-we-handle-rumors",
    title: "Unverified: a report is circulating, and here's what we will and won't publish",
    dek: "When an unconfirmed personal claim spreads, our default is restraint. We explain the standard rather than amplify the rumor.",
    status: "unverified",
    author: "MyKStars",
    date: "2026-06-20T16:00:00+09:00",
    body: [
      "Unverified reports, especially about anyone's private life, travel faster than the facts behind them. Our policy is simple: we do not repeat an unconfirmed personal claim as if it were established, and we never build a gallery whose only purpose is to capitalize on one.",
      "When something is genuinely newsworthy but unconfirmed, we say plainly what is known, what is not, and who would have to confirm it for the story to change. The 'Unverified' label exists so that status is never ambiguous.",
    ],
    related: {},
  },
];
