import type { Article, Source } from "@/lib/types";
import { FESTIVAL, NEWS1, NEWSEN, OSEN, STAR_NEWS, STUDIO, VOGUE_KOREA } from "./sources";

const ATEEZ_BILLBOARD_WEEK_TWO: Source = {
  name: "Star News · Billboard 200 week two",
  url: "https://www.starnewskorea.com/music/2026/07/15/2026071509182154700",
  kind: "press",
};
const KATSEYE_WILD_CAMPAIGN: Source = {
  name: "Universal Music Japan · KATSEYE",
  url: "https://www.universal-music.co.jp/katseye/news/2026-05-27/",
  kind: "official",
};
const JYP_FY26_Q1: Source = {
  name: "JYP Entertainment · FY26 Q1 Earnings Note",
  url: "https://www.jype.com/Board/Detail?gubun=irdata&jbst_sq=6985",
  kind: "official",
};
const KOBIS_2026_YEARLY: Source = {
  name: "KOBIS · 2026 yearly box office",
  url: "https://www.koreanfilm.or.kr/eng/news/boxOffice_Yearly.jsp?mode=BOXOFFICE_YEAR&selectDt=2026",
  kind: "official",
};

// ---------------------------------------------------------------------------
// ARTICLES
// ---------------------------------------------------------------------------
export const articles: Article[] = [
  // --- 2026-07-15 Analysis run: two artist calls, one company and one industry flagship ---
  {
    slug: "katseye-wild-catalogue-win",
    title: "KATSEYE can turn *WILD* into a catalogue win",
    dek: "*BEAUTIFUL CHAOS* paired a No. 4 opening with 19 weeks of chart life. Three AMA wins and a 31-date arena sellout give the follow-up room to raise both the debut and the hold.",
    status: "analysis",
    pillar: "k-pop",
    author: "MyKStars",
    date: "2026-07-15T13:30:00+09:00",
    body: [
      "*BEAUTIFUL CHAOS* already paired a No. 4 opening with 19 weeks of chart life. Three American Music Award wins and a 31-date arena sellout give *WILD* enough expanded demand to raise both the debut and the hold.",
      "*Billboard Brasil* reported on July 6, 2025, that *BEAUTIFUL CHAOS* opened with 44,000 album-equivalent units: 30,000 album sales and 14,000 streaming-equivalent units from 21.36 million on-demand streams. *Billboard Japan* then recorded the EP at No. 43 in its nineteenth Billboard 200 week on the chart dated November 15, 2025. KATSEYE has already shown that its audience can keep listening after release week.",
      "The campaign is larger now. Universal Music Japan reported on May 27, 2026, that KATSEYE won all three of its nominated American Music Award categories and sold out all 31 dates of THE WILDWORLD TOUR in under 48 hours. Awards and arena sales measure attention and live demand, while preorder incentives can still concentrate album consumption in week one.",
      "The bullish call requires two results. *WILD* must open with at least 60,000 units and a top three rank on the Billboard 200 dated August 29, then remain in the top 50 in week four on September 19.",
    ],
    source: KATSEYE_WILD_CAMPAIGN,
    related: { artistSlugs: ["katseye"] },
  },
  {
    slug: "ateez-number-one-listening-test",
    title: "ATEEZ has mastered the No. 1 debut. The next test is listening",
    dek: "*GOLDEN HOUR : Part.5* set a career peak through sales, then fell to No. 19 in week two. Recurring US listening now carries the growth test.",
    status: "analysis",
    pillar: "k-pop",
    author: "MyKStars",
    date: "2026-07-15T12:00:00+09:00",
    body: [
      "*GOLDEN HOUR : Part.5* converted ATEEZ's collector base into a record Billboard 200 No. 1, but a 97.8 percent sales share and a fall from No. 1 to No. 19 in week two leave the group's next US growth test in recurring listening.",
      "On July 6, 2026, *Billboard Japan* reported 228,000 album-equivalent units for the chart dated July 11: 223,000 traditional sales and 5,000 streaming-equivalent units from 4.96 million on-demand streams. Yonhap reported on July 3 that Hanteo first-week sales exceeded 1.88 million, another group record.",
      "The strongest opposing case is durable demand. ATEEZ has nine Billboard 200 top 10 releases, while *GOLDEN HOUR : Part.5* remained No. 1 on World Albums and No. 2 on Top Album Sales in its second week, according to the July 15 *Star News* chart report. Those results confirm repeat purchasing strength. Multiweek Billboard 200 retention offers the clearer test of listening beyond the collector base.",
      "The checkpoint is the Billboard 200 dated September 12, the EP's tenth chart week. A top 100 rank overturns this bearish call. A position below No. 100, or an earlier exit, supports it.",
    ],
    source: ATEEZ_BILLBOARD_WEEK_TWO,
    related: { artistSlugs: ["ateez"] },
  },
  {
    slug: "jyp-tour-shop-release-calendar",
    title: "JYP's tour shops are becoming a second release calendar",
    dek: "Q1 revenue rose 32.1 percent without a major artist album. The next quarter will show whether tour-linked city shops can keep Blue Garage above a double-digit margin.",
    status: "analysis",
    pillar: "k-pop",
    author: "MyKStars",
    date: "2026-07-15T10:30:00+09:00",
    body: [
      "JYP Entertainment's first quarter shows that tour-linked city popups can create a profitable sales calendar between major-artist albums. The bullish call is that Blue Garage can keep double-digit margins after delayed online-order recognition rolls off.",
      "JYP's FY26 Q1 Earnings Note, published May 15, 2026, recorded KRW 186.0 billion in consolidated revenue, up 32.1 percent from the prior-year quarter. Operating profit reached KRW 33.4 billion, up 70.0 percent, for a 17.9 percent operating margin. The quarter carried no major-artist album, and physical-recording revenue fell 15.1 percent to KRW 25.2 billion.",
      "Touring commerce filled that gap. Merchandise revenue reached KRW 60.6 billion, up 85.2 percent, while concert revenue reached KRW 40.9 billion, up 88.7 percent. Together they supplied KRW 101.5 billion, or 54.6 percent of consolidated revenue. Blue Garage raised revenue 180.5 percent to KRW 40.9 billion and posted an 11.1 percent operating margin. JYP mapped TWICE-linked popups across five cities in late 2025 and seven in Q1, with nine more planned for Q2.",
      "That cadence gives one tour several local sales windows and spreads product drops across months. It also makes touring a second release calendar, with merchandise tied to a live event rather than one album week. The model can keep intellectual property earning while the recording slate is light, and Q1 shows that fans will follow the schedule across markets.",
      "The strongest counterargument sits in recognition timing and artist concentration. JYP said part of Q1 Blue Garage revenue came from online deliveries completed after Stray Kids' October 2025 encore and TWICE's tenth-anniversary popup. Its November 14, 2025, FY25 Q3 Earnings Note also recorded a 20.5 percent merchandise decline to KRW 40.0 billion when large project sales were absent. Blue Garage's cumulative operating margin then sat near 9 percent. Those figures expose the volatility behind a quarter led by TWICE and Stray Kids.",
      "JYP's FY26 Q2 Earnings Note, assessed by August 31, 2026, is the checkpoint. The bullish call holds if at least two of three marks are met: merchandise revenue of KRW 50 billion or more, a Blue Garage operating margin of at least 10 percent, and a consolidated operating margin of at least 17 percent. The nine planned Q2 popup cities make that report the direct test of repeatability.",
    ],
    source: JYP_FY26_Q1,
    related: { artistSlugs: ["twice", "stray-kids", "nmixx"] },
  },
  {
    slug: "korean-cinema-distributor-concentration",
    title: "Korean cinema's record quarter belongs to one distributor",
    dek: "Admissions reached a post-2020 Q1 high, while Showbox captured 55.4 percent of revenue. Its hold on 2026's three biggest Korean releases keeps the recovery concentrated.",
    status: "analysis",
    pillar: "k-movie",
    author: "MyKStars",
    date: "2026-07-15T09:00:00+09:00",
    body: [
      "Korean theatrical demand has rebounded, but Showbox's control of the three biggest 2026 Korean releases means the recovery is still a distributor concentration story rather than a broad market recovery.",
      "The Korean Film Council's annual report, published February 27, 2026, put 2025 box-office revenue at KRW 1.047 trillion and admissions at 106.09 million. Revenue fell 12.4 percent from 2024, while admissions fell 13.8 percent. That weak base made the first-quarter rebound welcome and left breadth as the harder test.",
      "KOFIC's April 29 report recorded KRW 318.0 billion in first-quarter revenue and 31.9 million admissions, the strongest Q1 results since 2020. Korean films captured 73.4 percent of revenue. Showbox releases generated KRW 176.3 billion, equal to 55.4 percent of the entire market, while second-place Disney Korea took KRW 43.1 billion and 13.6 percent. Audience demand returned around a concentrated slate.",
      "The live KOBIS yearly table on July 15 places *The King's Warden*, *Colony* and *Salmokji* as the three leading 2026 Korean releases, with 16.91 million, 5.90 million and 3.24 million admissions. Showbox distributed all three. The run gives the recovery real force, while one distributor's command of the largest titles leaves rival pipelines with little evidence of comparable scale.",
      "The strongest counterargument is the range inside Showbox's run. Romance, historical drama, horror and zombie action have all found audiences, which points to demand across genres rather than a single-film anomaly. Genre breadth within one distributor still leaves financing and distribution breadth narrow. A durable national recovery needs multiple companies to turn multiple films into events.",
      "KOBIS results through August 31, 2026, provide the checkpoint. This bearish call is overturned only if at least two of the five highest-grossing Korean films released in 2026 come from non-Showbox distributors and each exceeds three million admissions. Any result below that mark supports the concentration thesis.",
    ],
    source: KOBIS_2026_YEARLY,
    related: {},
  },
  // --- 2026-07-05 roster expansion: multi-artist analysis for the new subjects ---
  {
    slug: "arirang-numbers-reading",
    title: "Reading the *Arirang* return: what the numbers actually say",
    dek: "A No. 1 debut, a free show at Gwanghwamun, a sold-out stadium run: BTS's comeback is best understood as three different records at once.",
    status: "analysis",
    pillar: "k-pop",
    author: "MyKStars",
    date: "2026-07-03T09:00:00+09:00",
    body: [
      "Comebacks after a service gap usually restart an engine. *Arirang* skipped the warmup: a Billboard 200 No. 1, the biggest Korean first week of the year, and a tour that sold through its London, Paris and Los Angeles stadium legs before the first night.",
      "The subtler number is the free one. The Gwanghwamun show in March cost nothing to attend and worked as a statement of scale: the group's first full stage in nearly four years, held as a public event in the middle of Seoul rather than behind a paywall.",
      "What to watch next is durability: whether the album's tracks re-enter the global charts as the European and American legs roll through the summer. That is the version of momentum that outlives a release week.",
    ],
    source: NEWS1,
    related: { artistSlugs: ["bts"], gallerySlugs: ["bts-gwanghwamun-comeback", "bts-the-city-london"] },
  },
  {
    slug: "rookie-class-2026-first-week-curve",
    title: "The 2026 rookie class is bending the first-week curve",
    dek: "CORTIS and Hearts2Hearts turned respectable debuts into record sophomore weeks. The old rookie math no longer holds.",
    status: "analysis",
    pillar: "k-pop",
    author: "MyKStars",
    date: "2026-07-02T09:00:00+09:00",
    body: [
      "For years the informal bar for a strong rookie debut sat around two hundred thousand first-week copies. The 2026 class made that a floor, not a ceiling: CORTIS moved over 2.3 million copies of *GREENGREEN* in a week, and Hearts2Hearts set a personal best just short of six hundred thousand with *Lemon Tang*.",
      "The pattern is the same in both cases: a solid debut, then a sophomore release that scales five to ten times. The machinery behind it (global pre-saves, day-one tour announcements, festival slots booked before the first anniversary) compresses what used to be a three-year build into eighteen months.",
      "The question that matters for the rest of the year is whether the third release holds the altitude. That, more than any award, is what separates a class from a cohort.",
    ],
    source: STAR_NEWS,
    related: {
      artistSlugs: ["cortis", "hearts2hearts", "babymonster"],
      gallerySlugs: ["cortis-golden-disc-rookie", "hearts2hearts-lemon-tang-week"],
    },
  },
  {
    slug: "girl-group-brand-race-2026",
    title: "The mid-2026 girl group brand race, in three moves",
    dek: "IVE hold the top, BLACKPINK surge on the *Deadline* era, and LE SSERAFIM turn a Macarena sample into a tour setup.",
    status: "analysis",
    pillar: "k-pop",
    author: "MyKStars",
    date: "2026-06-30T09:00:00+09:00",
    body: [
      "Brand reputation indexes are a blunt instrument, but they move on real events. IVE's hold on first place tracks a comeback cycle that never quite cooled; BLACKPINK's climb follows the *Deadline* records; LE SSERAFIM's rise maps almost exactly onto the week 'BOOMPALA' landed.",
      "What the index cannot see is the touring map underneath it. All three acts spend the second half of 2026 on the road, which means the next six months of this race will be decided in arenas, not on release calendars.",
    ],
    source: STAR_NEWS,
    related: {
      artistSlugs: ["ive", "blackpink", "le-sserafim"],
      gallerySlugs: ["ive-blackhole-comeback", "le-sserafim-boompala-comeback"],
    },
  },
  {
    slug: "monochrome-concept-photos-2026",
    title: "Why monochrome concept photos are dominating 2026 comebacks",
    dek: "Black-and-white sets read as 'premium' and travel well across platforms. A look at why agencies keep reaching for them.",
    status: "analysis",
    pillar: "k-pop",
    author: "MyKStars",
    date: "2026-06-21T13:00:00+09:00",
    body: [
      "Strip the color out of a concept set and two things happen at once: the styling reads as more expensive, and the images survive the journey through dozens of feeds, reposts and compression passes without falling apart. That durability matters when a comeback lives or dies in the first six hours of sharing.",
      "Monochrome also sidesteps the seasonal-palette problem. A set shot in black and white doesn't date the way a hyper-specific color story does, which is useful when the same images will anchor an artist hub for months.",
      "The risk is sameness. When everyone reaches for the same restraint, the differentiation moves back to where it always lived: styling, casting of the photographer, and the strength of a single hero frame.",
    ],
    source: NEWSEN,
    related: { artistSlugs: ["newjeans", "stray-kids"] },
  },
  {
    slug: "the-airport-runway",
    title: "The airport runway: how a 5 a.m. departure became fashion theater",
    dek: "Incheon's press line is now a styled event in its own right. We trace how 'airport fashion' became a genre.",
    status: "analysis",
    pillar: "k-pop",
    author: "MyKStars",
    date: "2026-06-21T10:30:00+09:00",
    body: [
      "There is nothing accidental about an airport look. Outfits are planned, sometimes pulled from a brand the artist represents, and timed to a press line that everyone in the room knows is coming.",
      "For global fans, the airport set is often the first high-resolution sighting of an artist between official schedules, which is exactly why organized, credited airport galleries are one of the most-searched things in the fandom and one of the least well served in English.",
    ],
    source: OSEN,
    related: { artistSlugs: ["blackpink", "twice"], gallerySlugs: ["blackpink-incheon-airport"] },
  },
  {
    slug: "kdrama-global-default",
    title: "How global streaming made K-drama a default, not a niche",
    dek: "Korean series are now a standing fixture on the world's streaming charts. We look at what that changes for how they're covered.",
    status: "analysis",
    pillar: "k-drama",
    author: "MyKStars",
    date: "2026-06-21T08:00:00+09:00",
    body: [
      "A decade ago, finding a Korean drama with reliable English subtitles took effort. Now a new title can open simultaneously in dozens of countries and sit on a global top-ten chart by the weekend. The discovery problem has inverted from scarcity to overload.",
      "That shift moves the coverage gap. The audience no longer needs to be told a show exists; it needs help deciding what to start, where to watch it without hunting across four services, and who is in it. Organized, credited stills and a clear where-to-watch line do more work than a recap ever did.",
    ],
    source: STUDIO,
    related: { artistSlugs: ["kim-tae-ri", "park-eun-bin"], gallerySlugs: ["drama-production-presentation"] },
  },
  {
    slug: "casting-season",
    title: "Casting season: how to read the tea leaves of a lineup",
    dek: "A casting announcement is the first marketing beat of a drama. Here's what the portrait drop is really telling you.",
    status: "analysis",
    pillar: "k-drama",
    author: "MyKStars",
    date: "2026-06-20T12:00:00+09:00",
    body: [
      "The character-portrait drop that accompanies a casting confirmation is a genre of its own: styled, lit, and released on a schedule designed to seed months of anticipation before a single scene airs.",
      "Read the lineup and you can usually read the budget, the target audience, and the tone. A cross-pillar cast (an idol stepping into a lead, a film actor taking a television role) is its own signal, and one worth following across the rest of the site.",
    ],
    source: STUDIO,
    related: { artistSlugs: ["lee-min-ho", "park-eun-bin"], gallerySlugs: ["drama-casting-ensemble"] },
  },
  {
    slug: "idol-ambassador-economy",
    title: "The idol-as-ambassador economy",
    dek: "Pictorials and house campaigns have become many artists' main visual output between comebacks. A look at the loop.",
    status: "analysis",
    pillar: "fashion-beauty",
    author: "MyKStars",
    date: "2026-06-21T07:00:00+09:00",
    body: [
      "Between comebacks, the steady drumbeat of an artist's visual presence is increasingly fashion and beauty work: a magazine cover, a house campaign, a front-row appearance. For a photo-first publication, that work is a pillar of K-pop coverage in its own right.",
      "The mechanics are a loop. A campaign produces editorial imagery; the imagery travels through fan accounts; the reach justifies the next ambassadorship. Crediting the photographer, stylist and glam team is the part of the story everyone else leaves out, and we treat that credit line as reporting.",
    ],
    source: VOGUE_KOREA,
    related: { artistSlugs: ["jung-hoyeon", "cha-eunwoo"], gallerySlugs: ["vogue-korea-editorial"] },
  },
  {
    slug: "festival-circuit-explained",
    title: "The festival circuit, explained",
    dek: "Busan, Cannes, Berlin: why the photocall still matters in a streaming-first world, and what it signals for Korean film.",
    status: "analysis",
    pillar: "k-movie",
    author: "MyKStars",
    date: "2026-06-20T19:00:00+09:00",
    body: [
      "Theatrical admissions have softened, but the festival photocall has, if anything, grown in importance: it's the moment a film's images enter the global conversation, and where a director's standing is publicly recognized.",
      "For Korean cinema specifically, the circuit is a prestige engine that feeds back into everything else: the auteur whose film premieres at Busan is the same name a drama production wants attached, and the same face a fashion house wants in the front row.",
    ],
    source: FESTIVAL,
    related: { artistSlugs: ["park-chan-wook", "bong-joon-ho"], gallerySlugs: ["busan-opening-photocall"] },
  },
  {
    slug: "what-confirmed-means",
    title: "Confirmed: what this label means on MyKStars",
    dek: "We attach 'Confirmed' only to facts an official source has stated on the record, and we link that source every time.",
    status: "confirmed",
    author: "MyKStars",
    date: "2026-06-20T17:00:00+09:00",
    body: [
      "A 'Confirmed' label is a promise, not a flourish. We apply it only when a primary source (an agency notice, an official account, a venue, or the artist) has stated something on the record, and we link directly to that source so you can check it yourself.",
      "If a detail is reported by other outlets but not confirmed at the source, it does not get this label. That discipline is the whole point: the label has to mean something for it to be worth showing.",
    ],
    related: {},
  },
  {
    slug: "how-we-handle-rumors",
    title: "Unverified: a report is circulating, and here's what we will and won't publish",
    dek: "When an unconfirmed personal claim spreads, our default is restraint. We explain the standard rather than amplify the rumor.",
    status: "unverified",
    author: "MyKStars",
    date: "2026-06-20T16:00:00+09:00",
    body: [
      "Unverified reports, especially about anyone's private life, travel faster than the facts behind them. Our policy is simple: we do not repeat an unconfirmed personal claim as if it were established, and we never build a gallery whose only purpose is to capitalize on one.",
      "When something is genuinely newsworthy but unconfirmed, we say plainly what is known, what is not, and who would have to confirm it for the story to change. The 'Unverified' label exists so that status is never ambiguous.",
    ],
    related: {},
  },
];
