import type { Source, StarEvent } from "@/lib/types";
import { BILLBOARD } from "./sources";

// ---------------------------------------------------------------------------
// EVENTS — D-Day schedule of officially-announced concerts and fan meetings.
// ---------------------------------------------------------------------------
// Unlike the sample rankings above, these are REAL announced dates, compiled
// from official tour pages and reputable trade/fan press as of July 5, 2026. Each
// event links back to its source. The set leans toward post-NOW dates outside
// Korea (the international audience) so the upcoming-only page stays populated;
// a couple of Korea dates exist so the region filter has content there too.
// Dates are venue-LOCAL calendar dates (date-only) — see format.ts for why.
// Tour names are omitted where they could not be confirmed.
const SOOMPI: Source = { name: "Soompi", url: "https://www.soompi.com/article/1797016wpp/2026-k-pop-tour-masterlist-concerts-fan-meetings-and-more", kind: "press" };
const POLLSTAR: Source = { name: "Pollstar", url: "https://news.pollstar.com", kind: "press" };
const TICKETMASTER: Source = { name: "Ticketmaster", url: "https://www.ticketmaster.com", kind: "official" };
const STRAY_KIDS_TOUR: Source = { name: "Stray Kids official tour", url: "https://straykidstour.org", kind: "official" };
const TWICE_TOUR: Source = { name: "TWICE official tour", url: "https://twicetours.com", kind: "official" };
const IBIGHIT: Source = { name: "BIGHIT MUSIC", url: "https://ibighit.com/en/cortis/tour/", kind: "official" };
const WEVERSE: Source = { name: "Weverse notice", url: "https://weverse.io/lesserafim/notice/35577", kind: "official" };

export const events: StarEvent[] = [
  // --- North America ---
  {
    slug: "enhypen-blood-saga-oakland",
    headliner: "ENHYPEN",
    type: "concert",
    tour: "BLOOD SAGA World Tour",
    date: "2026-07-28",
    endDate: "2026-07-29",
    venue: "Oakland Arena",
    city: "Oakland",
    country: "United States",
    region: "north-america",
    source: BILLBOARD,
  },
  {
    slug: "ive-show-what-i-am-newark",
    headliner: "IVE",
    artistSlugs: ["ive"],
    type: "concert",
    tour: "SHOW WHAT I AM World Tour",
    date: "2026-07-25",
    venue: "Prudential Center",
    city: "Newark",
    country: "United States",
    region: "north-america",
    source: SOOMPI,
  },
  {
    slug: "mamamoo-reunion-los-angeles",
    headliner: "MAMAMOO",
    type: "concert",
    tour: "2026 Reunion Tour",
    date: "2026-08-25",
    venue: "Crypto.com Arena",
    city: "Los Angeles",
    country: "United States",
    region: "north-america",
    source: BILLBOARD,
  },
  {
    slug: "bts-arirang-los-angeles",
    headliner: "BTS",
    artistSlugs: ["bts"],
    type: "concert",
    tour: "ARIRANG World Tour",
    date: "2026-09-01",
    endDate: "2026-09-06",
    venue: "SoFi Stadium",
    city: "Los Angeles",
    country: "United States",
    region: "north-america",
    status: "sold-out",
    source: BILLBOARD,
    note: "Four nights: September 1, 2, 5 and 6.",
  },
  {
    slug: "cortis-lollapalooza-chicago",
    headliner: "CORTIS",
    artistSlugs: ["cortis"],
    type: "concert",
    date: "2026-08-01",
    venue: "Grant Park",
    city: "Chicago",
    country: "United States",
    region: "north-america",
    source: BILLBOARD,
    note: "Lollapalooza main-stage festival debut; official aftershow July 31 at House of Blues.",
  },
  {
    slug: "iu-world-tour-newark",
    headliner: "IU",
    artistSlugs: ["iu"],
    type: "concert",
    date: "2026-07-15",
    venue: "Prudential Center",
    city: "Newark",
    country: "United States",
    region: "north-america",
    source: TICKETMASTER,
    note: "Opening night of the 2026 North American run, ahead of the late-summer album.",
  },
  {
    slug: "aespa-synk-complexity-new-york",
    headliner: "aespa",
    artistSlugs: ["aespa"],
    type: "concert",
    tour: "SYNK : COMPLæXITY",
    date: "2026-09-18",
    venue: "UBS Arena",
    city: "Belmont Park, NY",
    country: "United States",
    region: "north-america",
    source: POLLSTAR,
  },
  {
    slug: "monsta-x-nexus-new-york",
    headliner: "MONSTA X",
    type: "concert",
    tour: "THE X : NEXUS World Tour",
    date: "2026-10-06",
    venue: "Infosys Theater at Madison Square Garden",
    city: "New York",
    country: "United States",
    region: "north-america",
    source: BILLBOARD,
  },
  {
    slug: "katseye-wildworld-new-york",
    headliner: "KATSEYE",
    type: "concert",
    tour: "THE WILDWORLD TOUR",
    date: "2026-10-24",
    endDate: "2026-10-25",
    venue: "UBS Arena",
    city: "Belmont Park, NY",
    country: "United States",
    region: "north-america",
    source: BILLBOARD,
  },
  {
    slug: "lisa-las-vegas-residency",
    headliner: "LISA",
    type: "concert",
    tour: "VIVA LA LISA",
    date: "2026-11-13",
    endDate: "2026-11-28",
    venue: "The Colosseum at Caesars Palace",
    city: "Las Vegas",
    country: "United States",
    region: "north-america",
    source: BILLBOARD,
    note: "First solo Las Vegas residency by a K-pop artist; four dates (November 13, 14, 27 and 28).",
  },
  {
    slug: "xg-the-core-newark",
    headliner: "XG",
    type: "concert",
    tour: "THE CORE World Tour",
    date: "2026-11-14",
    venue: "Prudential Center",
    city: "Newark",
    country: "United States",
    region: "north-america",
    source: BILLBOARD,
  },

  // --- Europe ---
  {
    slug: "bts-arirang-london",
    headliner: "BTS",
    artistSlugs: ["bts"],
    type: "concert",
    tour: "ARIRANG World Tour",
    date: "2026-07-06",
    endDate: "2026-07-07",
    venue: "Tottenham Hotspur Stadium",
    city: "London",
    country: "United Kingdom",
    region: "europe",
    status: "sold-out",
    source: BILLBOARD,
  },
  {
    slug: "bts-arirang-paris",
    headliner: "BTS",
    artistSlugs: ["bts"],
    type: "concert",
    tour: "ARIRANG World Tour",
    date: "2026-07-17",
    endDate: "2026-07-18",
    venue: "Stade de France",
    city: "Paris",
    country: "France",
    region: "europe",
    status: "sold-out",
    source: BILLBOARD,
  },
  {
    slug: "itzy-tunnel-vision-london",
    headliner: "ITZY",
    type: "concert",
    tour: "TUNNEL VISION World Tour",
    date: "2026-09-11",
    venue: "OVO Arena Wembley",
    city: "London",
    country: "United Kingdom",
    region: "europe",
    source: SOOMPI,
  },
  {
    slug: "itzy-tunnel-vision-paris",
    headliner: "ITZY",
    type: "concert",
    tour: "TUNNEL VISION World Tour",
    date: "2026-09-15",
    venue: "Zenith Paris, La Villette",
    city: "Paris",
    country: "France",
    region: "europe",
    source: SOOMPI,
  },

  // --- Asia ---
  {
    slug: "jaehyun-mono-bangkok",
    headliner: "Jaehyun",
    type: "fan-meeting",
    tour: "MONO Fan Concert",
    date: "2026-07-04",
    city: "Bangkok",
    country: "Thailand",
    region: "asia",
    source: SOOMPI,
  },
  {
    slug: "exo-exhorizon-tokyo",
    headliner: "EXO",
    type: "concert",
    tour: "EXO PLANET #6: EXhOrizon",
    date: "2026-07-11",
    endDate: "2026-07-12",
    venue: "LaLa arena TOKYO-BAY",
    city: "Funabashi",
    country: "Japan",
    region: "asia",
    source: SOOMPI,
    note: "Two nights at the Tokyo Bay arena.",
  },
  {
    slug: "babymonster-choom-kyocera-osaka",
    headliner: "BABYMONSTER",
    artistSlugs: ["babymonster"],
    type: "concert",
    tour: "Choom World Tour",
    date: "2026-09-22",
    endDate: "2026-09-23",
    venue: "Kyocera Dome Osaka",
    city: "Osaka",
    country: "Japan",
    region: "asia",
    source: SOOMPI,
    note: "The group's first solo dome dates.",
  },
  {
    slug: "byeon-woo-seok-secret-library-singapore",
    headliner: "Byeon Woo-seok",
    artistSlugs: ["byeon-woo-seok"],
    type: "fan-meeting",
    tour: "The Secret Library",
    date: "2026-09-18",
    venue: "The Star Theatre",
    city: "Singapore",
    country: "Singapore",
    region: "asia",
    source: SOOMPI,
  },
  // (2026-07-05: removed a "THE ROYAL" Tokyo fan meeting once listed here for
  // 2026-07-15 — verification showed it was his 2025-07-15 pre-enlistment
  // farewell, a year off; he is enlisted through early 2027.)
  {
    slug: "aespa-synk-complexity-taipei",
    headliner: "aespa",
    artistSlugs: ["aespa"],
    type: "concert",
    tour: "SYNK : COMPLæXITY",
    date: "2026-08-11",
    city: "Taipei",
    country: "Taiwan",
    region: "asia",
    source: SOOMPI,
  },
  {
    slug: "stray-kids-world-tour-tokyo",
    headliner: "Stray Kids",
    artistSlugs: ["stray-kids"],
    type: "concert",
    tour: "RUN IT World Tour",
    date: "2026-08-29",
    endDate: "2026-08-30",
    city: "Tokyo",
    country: "Japan",
    region: "asia",
    source: STRAY_KIDS_TOUR,
    ticketUrl: "https://straykidstour.org",
  },

  // --- Latin America ---
  {
    slug: "enhypen-blood-saga-mexico-city",
    headliner: "ENHYPEN",
    type: "concert",
    tour: "BLOOD SAGA World Tour",
    date: "2026-07-11",
    city: "Mexico City",
    country: "Mexico",
    region: "latin-america",
    source: BILLBOARD,
  },
  {
    slug: "aespa-synk-complexity-sao-paulo",
    headliner: "aespa",
    artistSlugs: ["aespa"],
    type: "concert",
    tour: "SYNK : COMPLæXITY",
    date: "2026-09-04",
    city: "São Paulo",
    country: "Brazil",
    region: "latin-america",
    source: POLLSTAR,
  },
  {
    slug: "stray-kids-world-tour-mexico-city",
    headliner: "Stray Kids",
    artistSlugs: ["stray-kids"],
    type: "concert",
    tour: "RUN IT World Tour",
    date: "2026-09-25",
    endDate: "2026-09-26",
    venue: "Estadio GNP Seguros",
    city: "Mexico City",
    country: "Mexico",
    region: "latin-america",
    source: TICKETMASTER,
    ticketUrl: "https://straykidstour.org",
  },

  // --- Korea (a couple of dates so the Korea filter has content) ---
  {
    slug: "twice-this-is-for-seoul",
    headliner: "TWICE",
    artistSlugs: ["twice"],
    type: "concert",
    tour: "THIS IS FOR World Tour",
    date: "2026-07-10",
    endDate: "2026-07-12",
    venue: "KSPO Dome",
    city: "Seoul",
    country: "South Korea",
    region: "korea",
    source: TWICE_TOUR,
    ticketUrl: "https://twicetours.com",
    note: "Three-night world tour finale.",
  },
  {
    slug: "stray-kids-world-tour-seoul",
    headliner: "Stray Kids",
    artistSlugs: ["stray-kids"],
    type: "concert",
    tour: "RUN IT World Tour",
    date: "2026-07-25",
    endDate: "2026-08-02",
    venue: "KSPO Dome",
    city: "Seoul",
    country: "South Korea",
    region: "korea",
    status: "sold-out",
    source: STRAY_KIDS_TOUR,
    ticketUrl: "https://straykidstour.org",
    note: "Five nights: July 25, 26, 29 and August 1, 2.",
  },
  {
    slug: "cortis-put-your-phone-down-incheon",
    headliner: "CORTIS",
    artistSlugs: ["cortis"],
    type: "concert",
    tour: "PUT YOUR PHONE DOWN",
    date: "2026-07-18",
    endDate: "2026-07-19",
    venue: "Inspire Arena",
    city: "Incheon",
    country: "South Korea",
    region: "korea",
    source: IBIGHIT,
    ticketUrl: "https://ibighit.com/en/cortis/tour/",
    note: "First world tour opens at home.",
  },
  {
    slug: "le-sserafim-pureflow-incheon",
    headliner: "LE SSERAFIM",
    artistSlugs: ["le-sserafim"],
    type: "concert",
    tour: "PUREFLOW",
    date: "2026-07-11",
    endDate: "2026-07-12",
    city: "Incheon",
    country: "South Korea",
    region: "korea",
    source: WEVERSE,
    note: "Second world tour opens its 23-city run.",
  },
];
