import type { Gallery, MediaItem, Orientation, Source } from "@/lib/types";
import {
  ALLURE_KOREA,
  ELLE_KOREA,
  FESTIVAL,
  NEWS1,
  NEWSEN,
  OSEN,
  STAR_NEWS,
  STUDIO,
  VOGUE_KOREA,
  W_KOREA,
} from "./sources";

// ---------------------------------------------------------------------------
// SAMPLE GALLERY DATA — every set below renders as a branded placeholder tile
// (kind: "placeholder"), standing in for permitted photography during early
// development. Captions describe generic public moments (airport arrivals, red
// carpets, press lines, photocalls) with neutral, factual language; every item
// carries a credit. Permitted imagery (a MediaAsset-backed kind: "image")
// replaces these as it lands.
// ---------------------------------------------------------------------------
function place(
  id: string,
  alt: string,
  credit: Source,
  tone = 0,
  orientation: Orientation = "portrait",
): MediaItem {
  return { id, kind: "placeholder", alt, credit, tone, orientation };
}

// A uniform set (all one orientation) — used where the format is consistent.
function placeSet(
  prefix: string,
  baseAlt: string,
  credit: Source,
  n: number,
  orientation: Orientation = "portrait",
): MediaItem[] {
  return Array.from({ length: n }, (_, i) =>
    place(`${prefix}-${i + 1}`, `${baseAlt}, frame ${i + 1}`, credit, i % 4, orientation),
  );
}

// A portrait-leaning mixed set with ~1 landscape every 3 frames — the realistic
// case (selca/full-body portrait, the recurring wide group/stage frame). The
// cadence keeps portrait dominant while breaking the single-column monotony.
function placeMixed(
  prefix: string,
  baseAlt: string,
  credit: Source,
  n: number,
): MediaItem[] {
  return Array.from({ length: n }, (_, i) => {
    const orientation: Orientation = i % 3 === 2 ? "landscape" : "portrait";
    return place(`${prefix}-${i + 1}`, `${baseAlt}, frame ${i + 1}`, credit, i % 4, orientation);
  });
}

// ---------------------------------------------------------------------------
// GALLERIES
// ---------------------------------------------------------------------------
export const galleries: Gallery[] = [
  // ===================== K-POP =====================
  {
    // First live Instagram set (2026-07-16): aespa's KISS N TELL concept run,
    // reinstating Instagram as click-to-reveal photo embeds (server test, never
    // rehosted). Every permalink is a real, web-verified official post carrying
    // its TRUE upload date. See docs/roster-playbook.md and lib/instagram-embed.ts.
    slug: "aespa-kiss-n-tell",
    publicationState: "published",
    title: "aespa count down to *KISS N TELL*",
    pillar: "k-pop",
    category: "comeback",
    artistSlugs: ["aespa"],
    event: "Japan mini-album countdown",
    date: "2026-07-02T18:00:00+09:00",
    source: { name: "aespa on Instagram", url: "https://www.instagram.com/aespa_official/", kind: "embed" },
    excerpt:
      "aespa's first Japan mini album *KISS N TELL* arrives July 24, and the official concept run rolls out member by member on Instagram.",
    cover: {
      id: "aespa-kiss-n-tell-cover",
      kind: "embed",
      platform: "instagram",
      embedUrl: "https://www.instagram.com/p/DaQWW3kE0ue/",
      alt: "aespa announce the *KISS N TELL* Japan mini album, out July 24",
      credit: { name: "@smtown", url: "https://www.instagram.com/p/DaQWW3kE0ue/", kind: "embed" },
      date: "2026-07-01",
      orientation: "square",
    },
    media: [
      {
        id: "aespa-kiss-n-tell-ningning",
        kind: "embed",
        platform: "instagram",
        embedUrl: "https://www.instagram.com/p/DaS3i0JlFRk/",
        alt: "aespa's Ningning in the *KISS N TELL* concept photos",
        credit: { name: "@aespa_official", url: "https://www.instagram.com/p/DaS3i0JlFRk/", kind: "embed" },
        date: "2026-07-02",
        orientation: "portrait",
      },
      {
        id: "aespa-kiss-n-tell-karina",
        kind: "embed",
        platform: "instagram",
        embedUrl: "https://www.instagram.com/p/DaS5rjxT5x6/",
        alt: "aespa's Karina in the *KISS N TELL* concept photos",
        credit: { name: "@smtown", url: "https://www.instagram.com/p/DaS5rjxT5x6/", kind: "embed" },
        date: "2026-07-02",
        orientation: "portrait",
      },
      {
        id: "aespa-kiss-n-tell-announce",
        kind: "embed",
        platform: "instagram",
        embedUrl: "https://www.instagram.com/p/DaQWW3kE0ue/",
        alt: "aespa announce the *KISS N TELL* Japan mini album, out July 24",
        credit: { name: "@smtown", url: "https://www.instagram.com/p/DaQWW3kE0ue/", kind: "embed" },
        date: "2026-07-01",
        orientation: "square",
      },
    ],
  },
  {
    // 2026-07-05 correction: the prior "comeback showcase" set described an event
    // that never happened (and embedded a 2024 reel). Re-anchored to the verified
    // real moment: ADOR-confirmed pre-production sessions in Copenhagen, April
    // 13 to 17, 2026, with Haerin, Hyein and Hanni. See docs/roster-playbook.md.
    slug: "newjeans-copenhagen-sessions",
    publicationState: "archived",
    title: "NewJeans regroup in Copenhagen",
    pillar: "k-pop",
    category: "event",
    artistSlugs: ["newjeans"],
    event: "ADOR pre-production sessions",
    date: "2026-04-17T18:00:00+09:00",
    source: NEWS1,
    excerpt:
      "The first confirmed NewJeans activity of 2026: pre-production sessions in Copenhagen, confirmed by ADOR, with three members at work.",
    cover: place("newjeans-cph-cover", "NewJeans members arriving for the Copenhagen sessions", NEWS1, 2),
    media: placeMixed("newjeans-cph", "NewJeans Copenhagen sessions", NEWS1, 8),
  },
  {
    slug: "blackpink-incheon-airport",
    publicationState: "archived",
    title: "BLACKPINK at Incheon, ahead of a tour leg",
    pillar: "k-pop",
    category: "airport",
    tags: ["pictorial"],
    artistSlugs: ["blackpink"],
    event: "Incheon International Airport",
    date: "2026-06-21T18:00:00+09:00",
    source: OSEN,
    excerpt: "Departure looks captured in the Incheon airport press line.",
    cover: place("blackpink-cover", "BLACKPINK arriving at Incheon airport", OSEN, 0),
    media: placeSet("blackpink", "BLACKPINK at Incheon airport", OSEN, 8),
  },
  {
    slug: "stray-kids-music-show",
    publicationState: "archived",
    title: "Stray Kids work the comeback stage",
    pillar: "k-pop",
    category: "comeback",
    artistSlugs: ["stray-kids"],
    event: "Music-show comeback stage",
    date: "2026-06-21T16:00:00+09:00",
    source: NEWSEN,
    excerpt: "Performance frames from the week's music-show comeback.",
    cover: place("skz-cover", "Stray Kids on the comeback stage", NEWSEN, 3, "landscape"),
    media: placeMixed("skz", "Stray Kids comeback stage", NEWSEN, 7),
  },
  {
    slug: "aespa-fan-meet",
    publicationState: "archived",
    title: "aespa, up close at the fan meet",
    pillar: "k-pop",
    category: "event",
    artistSlugs: ["aespa"],
    event: "Fan meet",
    date: "2026-06-21T15:00:00+09:00",
    source: NEWS1,
    excerpt: "Stage and audience moments from the fan meet.",
    cover: place("aespa-cover", "aespa greeting fans at the fan meet", NEWS1, 1),
    media: placeMixed("aespa", "aespa fan meet", NEWS1, 6),
  },
  {
    slug: "iu-baeksang-red-carpet",
    publicationState: "archived",
    title: "IU on an awards-night red carpet",
    pillar: "k-pop",
    category: "red-carpet",
    tags: ["pictorial"],
    artistSlugs: ["iu"],
    event: "Awards ceremony",
    date: "2026-06-21T14:00:00+09:00",
    source: STAR_NEWS,
    excerpt: "Arrival and pose frames from the awards red carpet.",
    cover: place("iu-cover", "IU on the Baeksang Arts Awards red carpet", STAR_NEWS, 2),
    media: placeSet("iu", "IU on the Baeksang red carpet", STAR_NEWS, 6),
  },
  {
    slug: "cha-eunwoo-w-korea",
    publicationState: "archived",
    title: "Cha Eun-woo for *W Korea*",
    pillar: "k-pop",
    category: "pictorial",
    artistSlugs: ["cha-eunwoo"],
    event: "W Korea pictorial",
    date: "2026-06-21T12:00:00+09:00",
    source: W_KOREA,
    excerpt: "A licensed pictorial preview: the buy-the-issue funnel attaches here.",
    cover: place("eunwoo-cover", "Cha Eun-woo *W Korea* pictorial, cover look", W_KOREA, 3),
    media: placeSet("eunwoo", "Cha Eun-woo *W Korea* pictorial", W_KOREA, 6),
  },
  {
    slug: "twice-incheon-airport",
    publicationState: "archived",
    title: "TWICE depart from Incheon",
    pillar: "k-pop",
    category: "airport",
    artistSlugs: ["twice"],
    event: "Incheon International Airport",
    date: "2026-06-21T11:00:00+09:00",
    source: OSEN,
    excerpt: "Airport-fashion frames from the morning departure.",
    cover: place("twice-cover", "TWICE departing from Incheon airport", OSEN, 0),
    media: placeSet("twice", "TWICE at Incheon airport", OSEN, 7),
  },

  // ===================== K-DRAMA =====================
  {
    slug: "drama-production-presentation",
    publicationState: "archived",
    title: "A new series, unveiled at its production presentation",
    pillar: "k-drama",
    category: "stills",
    artistSlugs: ["kim-tae-ri", "park-eun-bin"],
    event: "Production presentation",
    date: "2026-06-21T17:30:00+09:00",
    source: STUDIO,
    excerpt: "First stills and cast frames from the production presentation of an upcoming drama.",
    cover: place("drama-pp-cover", "Cast at a drama production presentation", STUDIO, 1, "landscape"),
    media: placeMixed("drama-pp", "Drama production presentation", STUDIO, 7),
  },
  {
    slug: "lee-min-ho-press-tour",
    publicationState: "archived",
    title: "Lee Min-ho on the drama press tour",
    pillar: "k-drama",
    category: "press",
    artistSlugs: ["lee-min-ho"],
    event: "Press conference",
    date: "2026-06-21T13:30:00+09:00",
    source: STAR_NEWS,
    excerpt: "Arrival and step-and-repeat frames from the drama's press conference.",
    cover: place("lmh-cover", "Lee Min-ho at a drama press conference", STAR_NEWS, 2),
    media: placeSet("lmh", "Lee Min-ho at the press conference", STAR_NEWS, 6),
  },
  {
    slug: "drama-awards-press-line",
    publicationState: "archived",
    title: "Park Eun-bin on the drama awards press line",
    pillar: "k-drama",
    category: "press",
    tags: ["red-carpet"],
    artistSlugs: ["park-eun-bin"],
    event: "Drama awards",
    date: "2026-06-20T22:00:00+09:00",
    source: NEWS1,
    excerpt: "Press-line frames from the television drama awards.",
    cover: place("peb-cover", "Park Eun-bin on the drama awards press line", NEWS1, 3),
    media: placeSet("peb", "Park Eun-bin on the awards press line", NEWS1, 6),
  },
  {
    slug: "historical-series-stills",
    publicationState: "archived",
    title: "Stills from a new historical series",
    pillar: "k-drama",
    category: "stills",
    artistSlugs: ["kim-tae-ri"],
    event: "Drama stills",
    date: "2026-06-20T15:00:00+09:00",
    source: STUDIO,
    excerpt: "Wide-format production stills from an upcoming historical drama.",
    cover: place("hist-cover", "Production still from a historical drama", STUDIO, 0, "landscape"),
    media: placeSet("hist", "Historical drama still", STUDIO, 6, "landscape"),
  },
  {
    slug: "drama-casting-ensemble",
    publicationState: "archived",
    title: "Casting confirmed: the ensemble for an upcoming series",
    pillar: "k-drama",
    category: "casting",
    artistSlugs: ["lee-min-ho", "park-eun-bin"],
    event: "Casting announcement",
    date: "2026-06-20T11:00:00+09:00",
    source: STUDIO,
    excerpt: "Character portraits released with the casting announcement.",
    cover: place("cast-cover", "Character portrait from a casting announcement", STUDIO, 2),
    media: placeSet("cast", "Casting announcement portrait", STUDIO, 6),
  },

  // ===================== FASHION & BEAUTY =====================
  {
    slug: "vogue-korea-editorial",
    publicationState: "archived",
    title: "Jung Ho-yeon, a *Vogue Korea* editorial",
    pillar: "fashion-beauty",
    category: "pictorial",
    artistSlugs: ["jung-hoyeon"],
    event: "Vogue Korea editorial",
    date: "2026-06-21T09:30:00+09:00",
    source: VOGUE_KOREA,
    excerpt: "A licensed editorial preview: full-length portrait styling.",
    cover: place("vogue-cover", "Jung Ho-yeon *Vogue Korea* editorial, cover look", VOGUE_KOREA, 3),
    media: placeSet("vogue", "Jung Ho-yeon *Vogue Korea* editorial", VOGUE_KOREA, 6),
  },
  {
    slug: "luxury-house-campaign",
    publicationState: "archived",
    title: "A luxury-house campaign, shot in Seoul",
    pillar: "fashion-beauty",
    category: "campaign",
    artistSlugs: ["jung-hoyeon"],
    event: "Brand campaign",
    date: "2026-06-20T18:00:00+09:00",
    source: VOGUE_KOREA,
    excerpt: "Campaign imagery from a luxury-house ambassadorship.",
    cover: place("campaign-cover", "Luxury-house campaign key visual", VOGUE_KOREA, 1, "landscape"),
    media: placeMixed("campaign", "Luxury-house campaign", VOGUE_KOREA, 6),
  },
  {
    slug: "seoul-fashion-week-front-row",
    publicationState: "archived",
    title: "Seoul Fashion Week: the front row",
    pillar: "fashion-beauty",
    category: "fashion-week",
    artistSlugs: ["aespa", "jung-hoyeon"],
    event: "Seoul Fashion Week",
    date: "2026-06-20T13:00:00+09:00",
    source: W_KOREA,
    excerpt: "Front-row arrivals and looks from Seoul Fashion Week.",
    cover: place("sfw-cover", "Front-row arrival at Seoul Fashion Week", W_KOREA, 2),
    media: placeMixed("sfw", "Seoul Fashion Week front row", W_KOREA, 7),
  },

  // ===================== K-MOVIE =====================
  {
    slug: "busan-opening-photocall",
    publicationState: "archived",
    title: "Busan festival: the opening photocall",
    pillar: "k-movie",
    category: "festival",
    artistSlugs: ["park-chan-wook", "bong-joon-ho", "kim-tae-ri"],
    event: "Busan International Film Festival",
    date: "2026-06-21T11:30:00+09:00",
    source: FESTIVAL,
    excerpt: "Directors and cast at the festival's opening photocall.",
    cover: place("biff-cover", "Opening photocall at the Busan film festival", FESTIVAL, 0, "landscape"),
    media: placeMixed("biff", "Busan festival opening photocall", FESTIVAL, 7),
  },
  {
    slug: "director-in-focus",
    publicationState: "archived",
    title: "Director in focus: a career retrospective",
    pillar: "k-movie",
    category: "director",
    artistSlugs: ["park-chan-wook"],
    event: "Retrospective",
    date: "2026-06-20T20:00:00+09:00",
    source: FESTIVAL,
    excerpt: "Portraits and on-stage frames from a director retrospective Q&A.",
    cover: place("retro-cover", "Director on stage for a retrospective Q&A", FESTIVAL, 3),
    media: placeMixed("retro", "Director retrospective", FESTIVAL, 6),
  },

  // ----- additional K-POP sets (depth for the home band + /k-pop) -----
  {
    slug: "twice-music-bank-comeback",
    publicationState: "archived",
    title: "TWICE light up the comeback stage",
    pillar: "k-pop",
    category: "comeback",
    artistSlugs: ["twice"],
    event: "Music-show comeback stage",
    date: "2026-06-20T20:00:00+09:00",
    source: NEWSEN,
    excerpt: "Performance frames from the week's music-show comeback stage.",
    cover: place("twice-mb-cover", "TWICE on the comeback stage", NEWSEN, 1, "landscape"),
    media: placeMixed("twice-mb", "TWICE comeback stage", NEWSEN, 7),
  },
  {
    slug: "stray-kids-variety-appearance",
    publicationState: "archived",
    title: "Stray Kids drop by a variety set",
    pillar: "k-pop",
    category: "event",
    artistSlugs: ["stray-kids"],
    event: "Variety show appearance",
    date: "2026-06-19T20:00:00+09:00",
    source: NEWS1,
    excerpt: "Behind-the-scenes frames from a variety-show guest spot.",
    cover: place("skz-var-cover", "Stray Kids on a variety set", NEWS1, 2, "landscape"),
    media: placeMixed("skz-var", "Stray Kids variety appearance", NEWS1, 6),
  },

  // ----- 2026-07-05 roster expansion: new K-POP subjects, each anchored to a
  // web-verified real moment (docs/roster-playbook.md rule 2) -----
  {
    slug: "bts-the-city-london",
    publicationState: "archived",
    title: "BTS THE CITY takes over London",
    pillar: "k-pop",
    category: "event",
    artistSlugs: ["bts"],
    event: "BTS THE CITY, London",
    date: "2026-07-04T20:00:00+09:00",
    source: STAR_NEWS,
    excerpt:
      "The citywide fan activation opens ahead of the ARIRANG tour's Tottenham Hotspur Stadium nights.",
    cover: place("bts-city-cover", "BTS THE CITY signage lighting up central London", STAR_NEWS, 0),
    media: placeMixed("bts-city", "BTS THE CITY London activation", STAR_NEWS, 7),
  },
  {
    slug: "bts-gwanghwamun-comeback",
    publicationState: "archived",
    title: "BTS pack Gwanghwamun for the comeback",
    pillar: "k-pop",
    category: "event",
    artistSlugs: ["bts"],
    event: "BTS THE COMEBACK LIVE, Gwanghwamun Square",
    date: "2026-03-21T20:00:00+09:00",
    source: NEWS1,
    excerpt:
      "Frames from the free outdoor show in central Seoul, the first full-group stage in nearly four years, one day after *Arirang* arrived.",
    cover: place("bts-gwang-cover", "BTS on the Gwanghwamun Square stage", NEWS1, 3, "landscape"),
    media: placeMixed("bts-gwang", "BTS comeback show at Gwanghwamun Square", NEWS1, 9),
  },
  {
    slug: "seventeen-carat-land",
    publicationState: "archived",
    title: "SEVENTEEN scale CARAT LAND up to a stadium",
    pillar: "k-pop",
    category: "event",
    artistSlugs: ["seventeen"],
    event: "SEVENTEEN in CARAT LAND",
    date: "2026-06-20T19:00:00+09:00",
    source: OSEN,
    excerpt:
      "The tenth-anniversary fan meeting fills Incheon Asiad Main Stadium across two nights.",
    cover: place("svt-cl-cover", "SEVENTEEN greeting the crowd at CARAT LAND", OSEN, 1, "landscape"),
    media: placeMixed("svt-cl", "SEVENTEEN in CARAT LAND fan meeting", OSEN, 8),
  },
  {
    slug: "ive-blackhole-comeback",
    publicationState: "archived",
    title: "IVE pull the room into 'BLACKHOLE'",
    pillar: "k-pop",
    category: "comeback",
    artistSlugs: ["ive"],
    event: "*REVIVE+* comeback week",
    date: "2026-02-23T19:00:00+09:00",
    source: NEWSEN,
    excerpt:
      "Comeback-week performance frames from the *REVIVE+* title track's first stages.",
    cover: place("ive-bh-cover", "IVE on the 'BLACKHOLE' comeback stage", NEWSEN, 2, "landscape"),
    media: placeMixed("ive-bh", "IVE 'BLACKHOLE' comeback stage", NEWSEN, 7),
  },
  {
    slug: "cortis-golden-disc-rookie",
    publicationState: "archived",
    title: "CORTIS take Rookie of the Year in Taipei",
    pillar: "k-pop",
    category: "event",
    tags: ["red-carpet"],
    artistSlugs: ["cortis"],
    event: "40th Golden Disc Awards",
    date: "2026-01-10T21:00:00+09:00",
    source: STAR_NEWS,
    excerpt:
      "Red-carpet and acceptance frames from the Taipei Dome ceremony that crowned the rookie class.",
    cover: place("cortis-gda-cover", "CORTIS accepting Rookie of the Year", STAR_NEWS, 0),
    media: placeMixed("cortis-gda", "CORTIS at the Golden Disc Awards", STAR_NEWS, 8),
  },
  {
    slug: "cortis-nba-celebrity-game",
    publicationState: "archived",
    title: "CORTIS bring K-pop to the NBA Celebrity Game",
    pillar: "k-pop",
    category: "event",
    artistSlugs: ["cortis"],
    event: "NBA All-Star Celebrity Game halftime",
    date: "2026-02-13T14:00:00+09:00",
    source: NEWS1,
    excerpt:
      "Halftime-stage frames from the Kia Forum, the first K-pop act to play the Celebrity Game.",
    cover: place("cortis-nba-cover", "CORTIS at halftime of the NBA Celebrity Game", NEWS1, 1, "landscape"),
    media: placeMixed("cortis-nba", "CORTIS NBA Celebrity Game halftime", NEWS1, 7),
  },
  {
    slug: "hearts2hearts-lemon-tang-week",
    publicationState: "archived",
    title: "Hearts2Hearts squeeze summer into *Lemon Tang*",
    pillar: "k-pop",
    category: "comeback",
    artistSlugs: ["hearts2hearts"],
    event: "*Lemon Tang* comeback week",
    date: "2026-06-22T19:00:00+09:00",
    source: NEWSEN,
    excerpt:
      "Release-week stage and fan-event frames as the mini album posts the group's best first week yet.",
    cover: place("h2h-lt-cover", "Hearts2Hearts on the *Lemon Tang* comeback stage", NEWSEN, 2, "landscape"),
    media: placeMixed("h2h-lt", "Hearts2Hearts *Lemon Tang* comeback week", NEWSEN, 8),
  },
  {
    slug: "babymonster-choom-tour-opener",
    publicationState: "archived",
    title: "BABYMONSTER open the *Choom* tour at home",
    pillar: "k-pop",
    category: "event",
    artistSlugs: ["babymonster"],
    event: "Choom World Tour, Seoul opener",
    date: "2026-06-26T20:00:00+09:00",
    source: OSEN,
    excerpt:
      "Opening-night frames from Jamsil as the second world tour gets moving.",
    cover: place("bm-choom-cover", "BABYMONSTER opening the Choom world tour in Seoul", OSEN, 3, "landscape"),
    media: placeMixed("bm-choom", "BABYMONSTER Choom tour opener", OSEN, 8),
  },
  {
    slug: "le-sserafim-boompala-comeback",
    publicationState: "archived",
    title: "LE SSERAFIM go Latin house with 'BOOMPALA'",
    pillar: "k-pop",
    category: "comeback",
    artistSlugs: ["le-sserafim"],
    event: "*PUREFLOW pt.1* comeback week",
    date: "2026-05-22T19:00:00+09:00",
    source: NEWSEN,
    excerpt:
      "First-week performance frames from the single that set up the PUREFLOW tour.",
    cover: place("lsf-bp-cover", "LE SSERAFIM on the 'BOOMPALA' stage", NEWSEN, 1, "landscape"),
    media: placeMixed("lsf-bp", "LE SSERAFIM 'BOOMPALA' comeback stage", NEWSEN, 7),
  },

  // ----- additional K-DRAMA sets -----
  {
    slug: "drama-ost-release",
    publicationState: "archived",
    title: "Park Eun-bin lends her voice to a new OST",
    pillar: "k-drama",
    category: "ost",
    artistSlugs: ["park-eun-bin"],
    event: "OST release",
    date: "2026-06-19T18:00:00+09:00",
    source: STUDIO,
    excerpt: "Recording-booth and release frames from a drama OST.",
    cover: place("ost-cover", "OST recording session still", STUDIO, 3),
    media: placeMixed("ost", "Drama OST release", STUDIO, 6),
  },
  {
    slug: "drama-review-screening",
    publicationState: "archived",
    title: "Lee Min-ho at a drama review screening",
    pillar: "k-drama",
    category: "review",
    artistSlugs: ["lee-min-ho"],
    event: "Review screening",
    date: "2026-06-18T20:00:00+09:00",
    source: STAR_NEWS,
    excerpt: "Arrival and stage frames from a press review screening.",
    cover: place("review-cover", "Lee Min-ho at a review screening", STAR_NEWS, 1),
    media: placeSet("review", "Drama review screening", STAR_NEWS, 6),
  },
  {
    slug: "byeon-woo-seok-perfect-crown-press",
    publicationState: "archived",
    title: "Byeon Woo-seok and IU present *Perfect Crown*",
    pillar: "k-drama",
    category: "press",
    artistSlugs: ["byeon-woo-seok", "iu"],
    event: "Production press conference",
    date: "2026-04-06T15:00:00+09:00",
    source: STAR_NEWS,
    excerpt:
      "Step-and-repeat and stage frames from the Seoul press conference, four days before the premiere.",
    cover: place("bws-pc-cover", "Byeon Woo-seok and IU at the Perfect Crown press conference", STAR_NEWS, 2, "landscape"),
    media: placeMixed("bws-pc", "Perfect Crown press conference", STAR_NEWS, 8),
  },
  {
    slug: "byeon-woo-seok-bnb-set",
    publicationState: "archived",
    title: "Byeon Woo-seok checks into *Jae Seok's B&B Rules!*",
    pillar: "k-drama",
    category: "stills",
    artistSlugs: ["byeon-woo-seok"],
    event: "Variety set stills",
    date: "2026-05-26T12:00:00+09:00",
    source: STUDIO,
    excerpt:
      "Set stills from the actor's first fixed variety role, released with the premiere.",
    cover: place("bws-bnb-cover", "Byeon Woo-seok on the variety set", STUDIO, 0),
    media: placeMixed("bws-bnb", "Jae Seok's B&B Rules! set stills", STUDIO, 6),
  },

  // ----- additional FASHION & BEAUTY sets (the sparsest band) -----
  {
    slug: "cha-eunwoo-beauty-cover",
    publicationState: "archived",
    title: "Cha Eun-woo, an *Allure Korea* beauty cover",
    pillar: "fashion-beauty",
    category: "beauty",
    artistSlugs: ["cha-eunwoo"],
    event: "Allure Korea beauty story",
    date: "2026-06-20T10:00:00+09:00",
    source: ALLURE_KOREA,
    excerpt: "A licensed beauty-cover preview: skin-first styling.",
    cover: place("eunwoo-beauty-cover", "Cha Eun-woo *Allure Korea* beauty cover", ALLURE_KOREA, 2),
    media: placeSet("eunwoo-beauty", "Cha Eun-woo *Allure Korea* beauty story", ALLURE_KOREA, 6),
  },
  {
    slug: "aespa-elle-korea-summer",
    publicationState: "archived",
    title: "aespa cover *Elle Korea*'s summer issue",
    pillar: "fashion-beauty",
    category: "pictorial",
    artistSlugs: ["aespa"],
    event: "Elle Korea pictorial",
    date: "2026-06-19T10:00:00+09:00",
    source: ELLE_KOREA,
    excerpt: "A licensed editorial preview: full-group summer styling.",
    cover: place("aespa-elle-cover", "aespa *Elle Korea* summer cover", ELLE_KOREA, 3),
    media: placeSet("aespa-elle", "aespa *Elle Korea* summer editorial", ELLE_KOREA, 6),
  },
  {
    slug: "jung-hoyeon-milan-fashion-week",
    publicationState: "archived",
    title: "Jung Ho-yeon at Milan Fashion Week",
    pillar: "fashion-beauty",
    category: "fashion-week",
    artistSlugs: ["jung-hoyeon"],
    event: "Milan Fashion Week",
    date: "2026-06-18T22:00:00+09:00",
    source: W_KOREA,
    excerpt: "Front-row arrivals and looks from the Milan shows.",
    cover: place("hoyeon-milan-cover", "Jung Ho-yeon at Milan Fashion Week", W_KOREA, 0),
    media: placeMixed("hoyeon-milan", "Milan Fashion Week front row", W_KOREA, 6),
  },
  {
    slug: "beauty-house-skincare-campaign",
    publicationState: "archived",
    title: "A skincare house unveils its summer campaign",
    pillar: "fashion-beauty",
    category: "campaign",
    artistSlugs: ["jung-hoyeon"],
    event: "Brand campaign",
    date: "2026-06-17T12:00:00+09:00",
    source: ALLURE_KOREA,
    excerpt: "Campaign imagery from a beauty-house ambassadorship.",
    cover: place("skincare-cover", "Skincare campaign key visual", ALLURE_KOREA, 1, "landscape"),
    media: placeMixed("skincare", "Skincare campaign", ALLURE_KOREA, 6),
  },

  // ----- additional K-MOVIE sets (the other sparse band) -----
  {
    slug: "cannes-competition-photocall",
    publicationState: "archived",
    title: "Cannes: the competition photocall",
    pillar: "k-movie",
    category: "festival",
    artistSlugs: ["park-chan-wook", "kim-tae-ri"],
    event: "Cannes Film Festival",
    date: "2026-06-20T18:00:00+09:00",
    source: FESTIVAL,
    excerpt: "Director and cast at the competition photocall.",
    cover: place("cannes-cover", "Competition photocall at Cannes", FESTIVAL, 2, "landscape"),
    media: placeMixed("cannes", "Cannes competition photocall", FESTIVAL, 7),
  },
  {
    slug: "bong-joon-ho-press-conference",
    publicationState: "archived",
    title: "Bong Joon-ho fields the festival press",
    pillar: "k-movie",
    category: "review",
    artistSlugs: ["bong-joon-ho"],
    event: "Press conference",
    date: "2026-06-19T16:00:00+09:00",
    source: FESTIVAL,
    excerpt: "Stage and step-and-repeat frames from a festival press conference.",
    cover: place("bjh-press-cover", "Bong Joon-ho at a festival press conference", FESTIVAL, 0, "landscape"),
    media: placeSet("bjh-press", "Festival press conference", FESTIVAL, 6),
  },
  {
    slug: "director-masterclass",
    publicationState: "archived",
    title: "A director's masterclass, in full",
    pillar: "k-movie",
    category: "director",
    artistSlugs: ["park-chan-wook"],
    event: "Masterclass",
    date: "2026-06-18T19:00:00+09:00",
    source: FESTIVAL,
    excerpt: "On-stage frames from a director masterclass and audience Q and A.",
    cover: place("masterclass-cover", "Director on stage for a masterclass", FESTIVAL, 3),
    media: placeMixed("masterclass", "Director masterclass", FESTIVAL, 6),
  },
  {
    slug: "kim-tae-ri-indie-spotlight",
    publicationState: "archived",
    title: "Kim Tae-ri headlines an indie spotlight",
    pillar: "k-movie",
    category: "crossover",
    artistSlugs: ["kim-tae-ri"],
    event: "Indie showcase",
    date: "2026-06-17T19:00:00+09:00",
    source: FESTIVAL,
    excerpt: "Portraits and stage frames from an independent-film spotlight.",
    cover: place("indie-cover", "Kim Tae-ri at an indie film spotlight", FESTIVAL, 1),
    media: placeMixed("indie", "Indie film spotlight", FESTIVAL, 6),
  },
  // --- 2026-07-05 mosaic widening: landscape-led sets so the bands stop reading
  //     as a single portrait column (see docs/roster-playbook.md) ---
  {
    slug: "park-eun-bin-talk-show-taping",
    publicationState: "archived",
    title: "Park Eun-bin, wide frames from a talk-show taping",
    pillar: "k-drama",
    category: "press",
    artistSlugs: ["park-eun-bin"],
    event: "Broadcast promo circuit",
    date: "2026-06-26T20:00:00+09:00",
    source: STUDIO,
    excerpt: "Studio wides from a broadcast taping stop on the promo circuit.",
    cover: place("peb-taping-cover", "Park Eun-bin on a talk-show set", STUDIO, 1, "landscape"),
    media: placeSet("peb-taping", "Park Eun-bin talk-show taping", STUDIO, 7, "landscape"),
  },
  {
    slug: "festival-main-stage-wides",
    publicationState: "archived",
    title: "Festival season from the pit, shot wide",
    pillar: "k-pop",
    category: "event",
    artistSlugs: ["ive"],
    event: "University festival circuit",
    date: "2026-05-23T21:00:00+09:00",
    source: NEWSEN,
    excerpt: "Main-stage wides from the May festival run: full-stage frames with the crowd and lights in.",
    cover: place("fest-wides-cover", "IVE on a festival main stage", NEWSEN, 0, "landscape"),
    media: placeMixed("fest-wides", "Festival main stage", NEWSEN, 8),
  },
  {
    slug: "premiere-photocall-row",
    publicationState: "archived",
    title: "The premiere photocall, in a row",
    pillar: "k-movie",
    category: "festival",
    artistSlugs: ["park-chan-wook"],
    event: "Summer premiere circuit",
    date: "2026-06-30T19:30:00+09:00",
    source: FESTIVAL,
    excerpt: "Director and cast line up for the photocall row, the classic wide of premiere season.",
    cover: place("premiere-row-cover", "Park Chan-wook at a premiere photocall", FESTIVAL, 2, "landscape"),
    media: placeSet("premiere-row", "Premiere photocall row", FESTIVAL, 6, "landscape"),
  },
];
