import type { Artist } from "@/lib/types";

// ---------------------------------------------------------------------------
// PEOPLE — idols, actors, directors and models. Cross-pillar people carry more
// than one pillar/discipline (an idol who acts; an actor who works in film too).
// ---------------------------------------------------------------------------
export const artists: Artist[] = [
  {
    slug: "newjeans",
    name: "NewJeans",
    koreanName: "뉴진스",
    type: "group",
    careerStage: "established",
    coverageLevel: "active",
    publicationState: "published",
    lastVerified: "2026-07-15",
    disciplines: ["idol"],
    pillars: ["k-pop"],
    agency: "ADOR",
    debutYear: 2022,
    bio: "ADOR group with a clean, retro-leaning visual identity and a strong international following.",
    currentActivity: "ADOR confirmed in April 2026 that preparations for future group activity were under way.",
    social: [
      { platform: "instagram", url: "https://www.instagram.com/newjeans_official/", handle: "@newjeans_official" },
      { platform: "x", url: "https://x.com/NewJeans_ADOR", handle: "@NewJeans_ADOR" },
    ],
  },
  {
    slug: "blackpink",
    name: "BLACKPINK",
    koreanName: "블랙핑크",
    type: "group",
    careerStage: "icon",
    coverageLevel: "active",
    publicationState: "published",
    lastVerified: "2026-07-15",
    disciplines: ["idol"],
    pillars: ["k-pop"],
    agency: "YG Entertainment",
    debutYear: 2016,
    bio: "One of the most globally recognized K-pop groups, with a long record of fashion-house ambassadorships.",
    social: [
      { platform: "instagram", url: "https://www.instagram.com/blackpinkofficial/", handle: "@blackpinkofficial" },
      { platform: "x", url: "https://x.com/BLACKPINK", handle: "@BLACKPINK" },
    ],
  },
  {
    slug: "iu",
    name: "IU",
    koreanName: "아이유",
    type: "soloist",
    careerStage: "icon",
    coverageLevel: "active",
    publicationState: "published",
    lastVerified: "2026-07-15",
    disciplines: ["idol", "actor"],
    pillars: ["k-pop", "k-drama"],
    agency: "EDAM Entertainment",
    debutYear: 2008,
    bio: "Singer-songwriter and actor whose red-carpet and award-show appearances are widely covered.",
    social: [
      { platform: "instagram", url: "https://www.instagram.com/dlwlrma/", handle: "@dlwlrma" },
      { platform: "x", url: "https://x.com/_IUofficial", handle: "@_IUofficial" },
    ],
  },
  {
    slug: "stray-kids",
    name: "Stray Kids",
    koreanName: "스트레이 키즈",
    type: "group",
    careerStage: "established",
    coverageLevel: "active",
    publicationState: "published",
    lastVerified: "2026-07-15",
    disciplines: ["idol"],
    pillars: ["k-pop"],
    agency: "JYP Entertainment",
    debutYear: 2018,
    bio: "Self-producing group with a high-energy performance style and frequent music-show appearances.",
    social: [
      { platform: "instagram", url: "https://www.instagram.com/realstraykids/", handle: "@realstraykids" },
    ],
  },
  {
    slug: "aespa",
    name: "aespa",
    koreanName: "에스파",
    type: "group",
    careerStage: "established",
    coverageLevel: "active",
    publicationState: "published",
    lastVerified: "2026-07-15",
    disciplines: ["idol"],
    pillars: ["k-pop", "fashion-beauty"],
    agency: "SM Entertainment",
    debutYear: 2020,
    bio: "Concept-driven group whose fan events, showcases and fashion-week appearances draw large audiences.",
    social: [
      { platform: "instagram", url: "https://www.instagram.com/aespa_official/", handle: "@aespa_official" },
      { platform: "x", url: "https://x.com/aespa_official", handle: "@aespa_official" },
    ],
    // Instagram-embed hero (no licensed photo yet): aespa's KISS N TELL album
    // announcement, a real web-verified official post revealed on tap. 2026-07-16.
    hero: {
      id: "aespa-hero-kiss-n-tell",
      kind: "embed",
      platform: "instagram",
      embedUrl: "https://www.instagram.com/p/DaQWW3kE0ue/",
      alt: "aespa announce the *KISS N TELL* Japan mini album",
      credit: { name: "@smtown", url: "https://www.instagram.com/p/DaQWW3kE0ue/", kind: "embed" },
      date: "2026-07-01",
      orientation: "landscape",
    },
  },
  {
    slug: "cha-eunwoo",
    name: "Cha Eun-woo",
    koreanName: "차은우",
    type: "soloist",
    careerStage: "established",
    coverageLevel: "active",
    publicationState: "published",
    lastVerified: "2026-07-15",
    disciplines: ["idol", "actor"],
    pillars: ["k-pop", "k-drama"],
    agency: "Fantagio",
    debutYear: 2016,
    bio: "Idol and actor, a recurring face of fashion and beauty pictorials.",
    social: [
      { platform: "instagram", url: "https://www.instagram.com/eunwo.o_c/", handle: "@eunwo.o_c" },
      { platform: "youtube", url: "https://www.youtube.com/@offclCHAEUNWOO", handle: "@offclCHAEUNWOO" },
    ],
  },
  {
    slug: "twice",
    name: "TWICE",
    koreanName: "트와이스",
    type: "group",
    careerStage: "icon",
    coverageLevel: "active",
    publicationState: "published",
    lastVerified: "2026-07-15",
    disciplines: ["idol"],
    pillars: ["k-pop"],
    agency: "JYP Entertainment",
    debutYear: 2015,
    bio: "Long-running group with a steady touring schedule and heavy airport-fashion coverage.",
    social: [
      { platform: "instagram", url: "https://www.instagram.com/twicetagram/", handle: "@twicetagram" },
      { platform: "x", url: "https://x.com/JYPETWICE", handle: "@JYPETWICE" },
    ],
  },
  // --- K-Drama actors ---
  {
    slug: "lee-min-ho",
    name: "Lee Min-ho",
    koreanName: "이민호",
    type: "individual",
    careerStage: "icon",
    coverageLevel: "active",
    publicationState: "published",
    lastVerified: "2026-07-15",
    disciplines: ["actor"],
    pillars: ["k-drama"],
    debutYear: 2006,
    bio: "Television actor with a large international following, widely covered at premieres and brand events.",
    social: [
      { platform: "instagram", url: "https://www.instagram.com/actorleeminho/", handle: "@actorleeminho" },
    ],
  },
  {
    slug: "park-eun-bin",
    name: "Park Eun-bin",
    koreanName: "박은빈",
    type: "individual",
    careerStage: "established",
    coverageLevel: "active",
    publicationState: "published",
    lastVerified: "2026-07-15",
    disciplines: ["actor"],
    pillars: ["k-drama"],
    bio: "Television actor whose awards and press-event appearances draw heavy coverage.",
    social: [
      { platform: "instagram", url: "https://www.instagram.com/eunbining0904/", handle: "@eunbining0904" },
    ],
  },
  {
    slug: "kim-tae-ri",
    name: "Kim Tae-ri",
    koreanName: "김태리",
    type: "individual",
    careerStage: "established",
    coverageLevel: "active",
    publicationState: "published",
    lastVerified: "2026-07-15",
    disciplines: ["actor"],
    pillars: ["k-drama", "k-movie"],
    bio: "Actor working across film and television, a regular presence on the festival and press circuit.",
    social: [
      { platform: "instagram", url: "https://www.instagram.com/kimtaeri_official/", handle: "@kimtaeri_official" },
    ],
  },
  // --- K-Movie directors ---
  {
    slug: "park-chan-wook",
    name: "Park Chan-wook",
    koreanName: "박찬욱",
    type: "individual",
    careerStage: "icon",
    coverageLevel: "active",
    publicationState: "published",
    lastVerified: "2026-07-15",
    disciplines: ["director"],
    pillars: ["k-movie"],
    bio: "Film director and a recurring figure on the international festival circuit.",
  },
  {
    slug: "bong-joon-ho",
    name: "Bong Joon-ho",
    koreanName: "봉준호",
    type: "individual",
    careerStage: "icon",
    coverageLevel: "active",
    publicationState: "published",
    lastVerified: "2026-07-15",
    disciplines: ["director"],
    pillars: ["k-movie"],
    bio: "Film director widely covered at international festivals and premieres.",
  },
  // --- Fashion & Beauty (model/actor) ---
  {
    slug: "jung-hoyeon",
    name: "Jung Ho-yeon",
    koreanName: "정호연",
    type: "individual",
    careerStage: "established",
    coverageLevel: "active",
    publicationState: "published",
    lastVerified: "2026-07-15",
    disciplines: ["model", "actor"],
    pillars: ["fashion-beauty", "k-drama"],
    bio: "Model and actor, a fixture of luxury-house campaigns and fashion-week front rows.",
    social: [
      { platform: "instagram", url: "https://www.instagram.com/hoooooyeony/", handle: "@hoooooyeony" },
    ],
  },

  // --- Added in the 2026-07-05 roster expansion (docs/roster-playbook.md), with
  // profile facts, handles and era summaries reverified through 2026-07-15. ---
  {
    slug: "bts",
    name: "BTS",
    koreanName: "방탄소년단",
    type: "group",
    careerStage: "icon",
    coverageLevel: "active",
    publicationState: "published",
    lastVerified: "2026-07-15",
    disciplines: ["idol"],
    pillars: ["k-pop"],
    agency: "BIGHIT MUSIC",
    debutYear: 2013,
    bio: "Seven members back at full strength after military service, with the 2026 album *Arirang* and a sold-out stadium world tour marking the reunion.",
    social: [
      { platform: "instagram", url: "https://www.instagram.com/bts.bighitofficial/", handle: "@bts.bighitofficial" },
      { platform: "x", url: "https://x.com/BTS_twt", handle: "@BTS_twt" },
    ],
  },
  {
    slug: "seventeen",
    name: "SEVENTEEN",
    koreanName: "세븐틴",
    type: "group",
    careerStage: "icon",
    coverageLevel: "active",
    publicationState: "published",
    lastVerified: "2026-07-15",
    disciplines: ["idol"],
    pillars: ["k-pop"],
    agency: "PLEDIS Entertainment",
    debutYear: 2015,
    bio: "Thirteen-member self-producing group, fresh off a stadium world tour and a tenth-anniversary fan meeting, now rolling out unit releases.",
    social: [
      { platform: "instagram", url: "https://www.instagram.com/saythename_17/", handle: "@saythename_17" },
      { platform: "x", url: "https://x.com/pledis_17", handle: "@pledis_17" },
    ],
  },
  {
    slug: "ive",
    name: "IVE",
    koreanName: "아이브",
    type: "group",
    careerStage: "established",
    coverageLevel: "active",
    publicationState: "published",
    lastVerified: "2026-07-15",
    disciplines: ["idol"],
    pillars: ["k-pop"],
    agency: "Starship Entertainment",
    debutYear: 2021,
    bio: "Six-member Starship Entertainment group taking the SHOW WHAT I AM world tour across North America.",
    social: [
      { platform: "instagram", url: "https://www.instagram.com/ivestarship/", handle: "@ivestarship" },
      { platform: "x", url: "https://x.com/IVEstarship", handle: "@IVEstarship" },
    ],
  },
  {
    // Rookie graduation case (playbook rule 4): Golden Disc Rookie of the Year,
    // brand reputation top 10, and a 2.3M first week on *GREENGREEN* (Hanteo).
    slug: "cortis",
    name: "CORTIS",
    koreanName: "코르티스",
    type: "group",
    careerStage: "rookie",
    coverageLevel: "active",
    publicationState: "published",
    lastVerified: "2026-07-15",
    disciplines: ["idol"],
    pillars: ["k-pop"],
    agency: "BIGHIT MUSIC",
    debutYear: 2025,
    bio: "Five-member Big Hit group leading the 2026 rookie class: a Golden Disc win, an NBA halftime stage, and a first world tour opening in Incheon.",
    social: [
      { platform: "instagram", url: "https://www.instagram.com/cortis/", handle: "@cortis" },
      { platform: "x", url: "https://x.com/cortis_bighit", handle: "@cortis_bighit" },
    ],
  },
  {
    slug: "hearts2hearts",
    name: "Hearts2Hearts",
    koreanName: "하츠투하츠",
    type: "group",
    careerStage: "rookie",
    coverageLevel: "active",
    publicationState: "published",
    lastVerified: "2026-07-15",
    disciplines: ["idol"],
    pillars: ["k-pop"],
    agency: "SM Entertainment",
    debutYear: 2025,
    bio: "Eight-member SM group whose 'RUDE!' and *Lemon Tang* releases turned a solid 2025 debut into breakout 2026 scale.",
    social: [
      { platform: "instagram", url: "https://www.instagram.com/hearts2hearts/", handle: "@hearts2hearts" },
      { platform: "x", url: "https://x.com/Hearts2Hearts", handle: "@Hearts2Hearts" },
    ],
  },
  {
    slug: "babymonster",
    name: "BABYMONSTER",
    koreanName: "베이비몬스터",
    type: "group",
    careerStage: "rising",
    coverageLevel: "active",
    publicationState: "published",
    lastVerified: "2026-07-15",
    disciplines: ["idol"],
    pillars: ["k-pop"],
    agency: "YG Entertainment",
    debutYear: 2023,
    bio: "Seven-member YG group on a second world tour behind *Choom*, with their first Japanese dome dates booked for the fall.",
    social: [
      { platform: "instagram", url: "https://www.instagram.com/babymonster_ygofficial/", handle: "@babymonster_ygofficial" },
      { platform: "x", url: "https://x.com/ygbabymonster_", handle: "@ygbabymonster_" },
    ],
  },
  {
    slug: "le-sserafim",
    name: "LE SSERAFIM",
    koreanName: "르세라핌",
    type: "group",
    careerStage: "established",
    coverageLevel: "active",
    publicationState: "published",
    lastVerified: "2026-07-15",
    disciplines: ["idol"],
    pillars: ["k-pop"],
    agency: "Source Music",
    debutYear: 2022,
    bio: "Five-member Source Music group riding the Latin house single 'BOOMPALA' into PUREFLOW, their second world tour.",
    social: [
      { platform: "instagram", url: "https://www.instagram.com/le_sserafim/", handle: "@le_sserafim" },
      { platform: "x", url: "https://x.com/le_sserafim", handle: "@le_sserafim" },
    ],
  },
  // --- K-Drama (actor) ---
  {
    slug: "byeon-woo-seok",
    name: "Byeon Woo-seok",
    koreanName: "변우석",
    type: "individual",
    careerStage: "rising",
    coverageLevel: "active",
    publicationState: "published",
    lastVerified: "2026-07-15",
    disciplines: ["actor"],
    pillars: ["k-drama"],
    agency: "VARO Entertainment",
    debutYear: 2016,
    bio: "Leading man of *Lovely Runner* and *Perfect Crown*, now adding a Netflix variety turn and an Asia fan meeting tour to the run.",
    social: [
      { platform: "instagram", url: "https://www.instagram.com/byeonwooseok/", handle: "@byeonwooseok" },
    ],
  },

  // Added for the August 2026 edition. Every profile was reverified on
  // 2026-07-14 against the linked agency, label, broadcaster, or studio source.
  {
    slug: "katseye",
    name: "KATSEYE",
    type: "group",
    careerStage: "rising",
    coverageLevel: "active",
    publicationState: "published",
    lastVerified: "2026-07-15",
    disciplines: ["idol"],
    pillars: ["k-pop"],
    agency: "HYBE x Geffen Records",
    debutYear: 2024,
    bio: "Six-member global girl group created by HYBE and Geffen Records with a multinational lineup.",
    currentActivity: "The group is preparing the EP *WILD*, due August 14, 2026.",
    officialLinks: [
      { label: "Official profile", url: "https://www.katseye.world/story-of-katseye/" },
    ],
    hero: {
      id: "katseye-hybe-labels-2026",
      kind: "embed",
      alt: "KATSEYE in an official HYBE LABELS video",
      credit: {
        name: "HYBE LABELS",
        url: "https://www.youtube.com/watch?v=7F1ET2XHQfk",
        kind: "embed",
      },
      embedUrl: "https://www.youtube.com/watch?v=7F1ET2XHQfk",
      platform: "youtube",
      date: "2026-04-10",
    },
  },
  {
    slug: "illit",
    name: "ILLIT",
    type: "group",
    careerStage: "rising",
    coverageLevel: "active",
    publicationState: "published",
    lastVerified: "2026-07-15",
    disciplines: ["idol"],
    pillars: ["k-pop"],
    agency: "BELIFT LAB",
    debutYear: 2024,
    bio: "Five-member BELIFT LAB group whose catalog spans Korean and Japanese releases.",
    currentActivity: "The group released the album *MAMIHLAPINATAPAI* on April 30, 2026.",
    officialLinks: [
      { label: "Official profile", url: "https://beliftlab.com/artist/profile/ILLIT" },
    ],
    hero: {
      id: "illit-hybe-labels-2026",
      kind: "embed",
      alt: "ILLIT in an official HYBE LABELS video",
      credit: {
        name: "HYBE LABELS",
        url: "https://www.youtube.com/watch?v=bMhDJ0S0OBA",
        kind: "embed",
      },
      embedUrl: "https://www.youtube.com/watch?v=bMhDJ0S0OBA",
      platform: "youtube",
      date: "2026-04-30",
    },
  },
  {
    slug: "riize",
    name: "RIIZE",
    type: "group",
    careerStage: "rising",
    coverageLevel: "active",
    publicationState: "published",
    lastVerified: "2026-07-15",
    disciplines: ["idol"],
    pillars: ["k-pop"],
    agency: "SM Entertainment",
    debutYear: 2023,
    bio: "Six-member SM Entertainment group whose 2026 album *II* follows a 2023 debut.",
    currentActivity: "The group released *II* on June 15, 2026.",
    officialLinks: [
      { label: "Official profile", url: "https://www.riizeofficial.jp/profile/" },
    ],
    hero: {
      id: "riize-smtown-2026",
      kind: "embed",
      alt: "RIIZE in an official SMTOWN video",
      credit: {
        name: "SMTOWN",
        url: "https://www.youtube.com/watch?v=HDGCTtuW-Yo",
        kind: "embed",
      },
      embedUrl: "https://www.youtube.com/watch?v=HDGCTtuW-Yo",
      platform: "youtube",
      date: "2026-06-15",
    },
  },
  {
    slug: "nmixx",
    name: "NMIXX",
    type: "group",
    careerStage: "established",
    coverageLevel: "active",
    publicationState: "published",
    lastVerified: "2026-07-15",
    disciplines: ["idol"],
    pillars: ["k-pop"],
    agency: "JYP Entertainment, SQU4D",
    debutYear: 2022,
    bio: "Six-member JYP Entertainment group whose 2026 catalog includes *Heavy Serenade*.",
    currentActivity: "The group released *Heavy Serenade* on May 11, 2026.",
    officialLinks: [
      { label: "Official profile", url: "https://nmixx.jype.com/Default/Profile" },
    ],
    hero: {
      id: "nmixx-jyp-2026",
      kind: "embed",
      alt: "NMIXX in an official JYP Entertainment video",
      credit: {
        name: "JYP Entertainment",
        url: "https://www.youtube.com/watch?v=6Ycn9qZK09I",
        kind: "embed",
      },
      embedUrl: "https://www.youtube.com/watch?v=6Ycn9qZK09I",
      platform: "youtube",
      date: "2026-05-11",
    },
  },
  {
    slug: "tws",
    name: "TWS",
    type: "group",
    careerStage: "rising",
    coverageLevel: "active",
    publicationState: "published",
    lastVerified: "2026-07-15",
    disciplines: ["idol"],
    pillars: ["k-pop"],
    agency: "PLEDIS Entertainment",
    debutYear: 2024,
    bio: "Six-member PLEDIS Entertainment group active since its 2024 debut.",
    currentActivity: "The group is set to release *SODA SODA* on August 4, 2026.",
    officialLinks: [
      { label: "Official profile", url: "https://www.pledis.co.kr/en/artist/detail/TWS/profile/" },
    ],
    hero: {
      id: "tws-hybe-labels-2026",
      kind: "embed",
      alt: "TWS in an official HYBE LABELS video",
      credit: {
        name: "HYBE LABELS",
        url: "https://www.youtube.com/watch?v=MiO16KlMPaU",
        kind: "embed",
      },
      embedUrl: "https://www.youtube.com/watch?v=MiO16KlMPaU",
      platform: "youtube",
      date: "2026-04-27",
    },
  },
  {
    slug: "allday-project",
    name: "ALLDAY PROJECT",
    type: "group",
    careerStage: "rookie",
    coverageLevel: "active",
    publicationState: "published",
    lastVerified: "2026-07-15",
    disciplines: ["idol"],
    pillars: ["k-pop"],
    agency: "THEBLACKLABEL",
    debutYear: 2025,
    bio: "Five-member co-ed group from THEBLACKLABEL that debuted in 2025.",
    currentActivity: "The group released branded PUBG collaboration work in March 2026.",
    officialLinks: [
      { label: "Official profile", url: "https://en.tblshop.com/allday-project/profile.html" },
    ],
    hero: {
      id: "allday-project-pubg-2026",
      kind: "embed",
      alt: "ALLDAY PROJECT in an official PUBG collaboration video",
      credit: {
        name: "THEBLACKLABEL",
        url: "https://www.youtube.com/watch?v=LHUMzyMq084",
        kind: "embed",
      },
      embedUrl: "https://www.youtube.com/watch?v=LHUMzyMq084",
      platform: "youtube",
      date: "2026-03-09",
    },
  },
  {
    slug: "boynextdoor",
    name: "BOYNEXTDOOR",
    type: "group",
    careerStage: "rising",
    coverageLevel: "active",
    publicationState: "published",
    lastVerified: "2026-07-15",
    disciplines: ["idol"],
    pillars: ["k-pop"],
    agency: "KOZ Entertainment",
    debutYear: 2023,
    bio: "Six-member KOZ Entertainment group active across Korean and Japanese releases since its 2023 debut.",
    currentActivity: "The group released *HOME* on June 8, 2026.",
    officialLinks: [
      { label: "Official profile", url: "https://kozofficial.com/artist/profile/BOYNEXTDOOR?lang=en" },
    ],
    hero: {
      id: "boynextdoor-hybe-labels-2026",
      kind: "embed",
      alt: "BOYNEXTDOOR in an official HYBE LABELS video",
      credit: {
        name: "HYBE LABELS",
        url: "https://www.youtube.com/watch?v=zGsj0fDHB_s",
        kind: "embed",
      },
      embedUrl: "https://www.youtube.com/watch?v=zGsj0fDHB_s",
      platform: "youtube",
      date: "2026-06-08",
    },
  },
  {
    slug: "meovv",
    name: "MEOVV",
    type: "group",
    careerStage: "rookie",
    coverageLevel: "active",
    publicationState: "published",
    lastVerified: "2026-07-15",
    disciplines: ["idol"],
    pillars: ["k-pop"],
    agency: "THEBLACKLABEL",
    debutYear: 2024,
    bio: "Five-member THEBLACKLABEL group that debuted in 2024.",
    currentActivity: "The group released the EP *BITE NOW* on June 1, 2026.",
    officialLinks: [
      { label: "Official profile", url: "https://en.tblshop.com/meovv/profile.html" },
    ],
    hero: {
      id: "meovv-theblacklabel-2026",
      kind: "embed",
      alt: "MEOVV in an official THEBLACKLABEL video",
      credit: {
        name: "THEBLACKLABEL",
        url: "https://www.youtube.com/watch?v=aHM2RKeMaeM",
        kind: "embed",
      },
      embedUrl: "https://www.youtube.com/watch?v=aHM2RKeMaeM",
      platform: "youtube",
      date: "2026-06-01",
    },
  },
  {
    slug: "enhypen",
    name: "ENHYPEN",
    type: "group",
    careerStage: "established",
    coverageLevel: "active",
    publicationState: "published",
    lastVerified: "2026-07-15",
    disciplines: ["idol"],
    pillars: ["k-pop"],
    agency: "BELIFT LAB",
    debutYear: 2020,
    bio: "Six-member BELIFT LAB group with a 2026 tour schedule spanning Asia and North America.",
    currentActivity: "The group is carrying its 2026 tour schedule across Asia and North America.",
    officialLinks: [
      { label: "Official profile", url: "https://beliftlab.com/artist/profile/ENHYPEN?lang=en" },
    ],
    hero: {
      id: "enhypen-official-2026",
      kind: "embed",
      alt: "ENHYPEN in an official group video",
      credit: {
        name: "ENHYPEN",
        url: "https://www.youtube.com/watch?v=VVV2E5p8gs4",
        kind: "embed",
      },
      embedUrl: "https://www.youtube.com/watch?v=VVV2E5p8gs4",
      platform: "youtube",
      date: "2026-05-17",
    },
  },
  {
    slug: "ateez",
    name: "ATEEZ",
    type: "group",
    careerStage: "established",
    coverageLevel: "active",
    publicationState: "published",
    lastVerified: "2026-07-15",
    disciplines: ["idol"],
    pillars: ["k-pop"],
    agency: "KQ Entertainment",
    debutYear: 2018,
    bio: "Eight-member KQ Entertainment group with a global touring and album catalog built since 2018.",
    currentActivity: "The group released *GOLDEN HOUR : Part.5* on June 26, 2026.",
    officialLinks: [
      { label: "Official profile", url: "https://ateez-official.jp/profiles" },
    ],
    hero: {
      id: "ateez-kq-2026",
      kind: "embed",
      alt: "ATEEZ in an official KQ Entertainment video",
      credit: {
        name: "KQ ENTERTAINMENT",
        url: "https://www.youtube.com/watch?v=-q_S27LbNKU",
        kind: "embed",
      },
      embedUrl: "https://www.youtube.com/watch?v=-q_S27LbNKU",
      platform: "youtube",
      date: "2026-06-26",
    },
  },
  {
    slug: "roh-yoon-seo",
    name: "Roh Yoon-seo",
    type: "individual",
    careerStage: "rising",
    coverageLevel: "active",
    publicationState: "published",
    lastVerified: "2026-07-15",
    disciplines: ["actor", "model"],
    pillars: ["k-drama", "k-movie", "fashion-beauty"],
    agency: "MAA",
    debutYear: 2022,
    bio: "Actor and model working across streaming drama, film and fashion campaigns.",
    currentActivity: "She stars in the Netflix series *The East Palace*, which premieres July 17, 2026.",
    officialLinks: [
      { label: "Agency profile", url: "https://www.maa.co.kr/artists/roh-yoonseo" },
    ],
    hero: {
      id: "roh-yoon-seo-east-palace-2026",
      kind: "embed",
      alt: "Roh Yoon-seo in the official trailer for *The East Palace*",
      credit: {
        name: "Netflix",
        url: "https://www.youtube.com/watch?v=wBUkNE1l9DU",
        kind: "embed",
      },
      embedUrl: "https://www.youtube.com/watch?v=wBUkNE1l9DU",
      platform: "youtube",
      date: "2026-07-01",
    },
  },
  {
    slug: "lee-chae-min",
    name: "Lee Chae-min",
    type: "individual",
    careerStage: "rising",
    coverageLevel: "active",
    publicationState: "published",
    lastVerified: "2026-07-15",
    disciplines: ["actor", "model"],
    pillars: ["k-drama", "fashion-beauty"],
    agency: "VARO Entertainment",
    debutYear: 2021,
    bio: "Actor and model working across television, streaming series and fashion.",
    currentActivity: "He is attached to the Netflix unscripted series *Take a Hike!*.",
    officialLinks: [
      { label: "Agency profile", url: "https://varoent.co.kr/chaemin/" },
    ],
    hero: {
      id: "lee-chae-min-varo-playlist-2026",
      kind: "embed",
      alt: "Lee Chae-min in an official VARO Playlist video",
      credit: {
        name: "VARO Playlist",
        url: "https://www.youtube.com/watch?v=1vytCCcRjCw",
        kind: "embed",
      },
      embedUrl: "https://www.youtube.com/watch?v=1vytCCcRjCw",
      platform: "youtube",
      date: "2026-07-07",
    },
  },
  {
    slug: "choo-young-woo",
    name: "Choo Young-woo",
    type: "individual",
    careerStage: "rising",
    coverageLevel: "active",
    publicationState: "published",
    lastVerified: "2026-07-15",
    disciplines: ["actor"],
    pillars: ["k-drama"],
    agency: "J,WIDE-Company",
    debutYear: 2021,
    bio: "Television actor whose recent lead roles have expanded into Netflix productions.",
    currentActivity: "He is filming the Netflix drama *Long Vacation*.",
    officialLinks: [
      { label: "Agency profile", url: "http://www.jwide.co.kr/bbs/board.php?bo_table=21&wr_id=44" },
    ],
    hero: {
      id: "choo-young-woo-2022-portrait-hero",
      kind: "image",
      alt: "Choo Young-woo at SBS Radio in 2022",
      credit: {
        name: "SBS Radio 에라오",
        url: "https://commons.wikimedia.org/wiki/File:Choo_Young-woo_%EC%B6%94%EC%98%81%EC%9A%B0_in_2022.png",
        kind: "licensed",
      },
      src: "https://rbhajkwsmvbyafzrthwf.supabase.co/storage/v1/object/public/media/profiles/choo-young-woo/2026/choo-young-woo-2022-portrait.png",
      width: 725,
      height: 868,
      orientation: "portrait",
      assetId: "choo-young-woo-2022-portrait",
    },
  },
  {
    slug: "kim-min-ha",
    name: "Kim Min-ha",
    type: "individual",
    careerStage: "established",
    coverageLevel: "active",
    publicationState: "published",
    lastVerified: "2026-07-15",
    disciplines: ["actor"],
    pillars: ["k-drama", "k-movie"],
    agency: "Noon Company",
    debutYear: 2016,
    bio: "Actor working across Korean film, television and international series.",
    currentActivity: "She is attached to the Netflix series *Messily Ever After*.",
    officialLinks: [
      { label: "Agency profile", url: "http://www.nooncompany.kr/artists_profile.php?artist=30" },
    ],
    hero: {
      id: "kim-min-ha-2024-love-your-w-hero",
      kind: "image",
      alt: "Kim Min-ha at the Love Your W event in October 2024",
      credit: {
        name: "티비텐 TV10",
        url: "https://commons.wikimedia.org/wiki/File:Kim_Min-ha_in_October_2024.png",
        kind: "licensed",
      },
      src: "https://rbhajkwsmvbyafzrthwf.supabase.co/storage/v1/object/public/media/profiles/kim-min-ha/2026/kim-min-ha-2024-love-your-w.png",
      width: 2588,
      height: 3604,
      orientation: "portrait",
      assetId: "kim-min-ha-2024-love-your-w",
    },
  },
  {
    slug: "park-ji-hu",
    name: "Park Ji-hu",
    type: "individual",
    careerStage: "rising",
    coverageLevel: "active",
    publicationState: "published",
    lastVerified: "2026-07-15",
    disciplines: ["actor"],
    pillars: ["k-drama", "k-movie"],
    agency: "BH Entertainment",
    debutYear: 2016,
    bio: "Actor whose screen career began in childhood and now spans film and streaming series.",
    currentActivity: "She is in production on season two of *All of Us Are Dead*.",
    officialLinks: [
      { label: "Agency profile", url: "https://bhent.co.kr/artist/park-ji-hu/" },
    ],
    hero: {
      id: "park-ji-hu-2022-blue-dragon-hero",
      kind: "image",
      alt: "Park Ji-hu at the first Blue Dragon Series Awards in 2022",
      credit: {
        name: "BH Entertainment",
        url: "https://commons.wikimedia.org/wiki/File:20220719_Park_Ji-hu_(%EB%B0%95%EC%A7%80%ED%9B%84)_1st_Blue_Dragon_Series_Awards.jpg",
        kind: "licensed",
      },
      src: "https://rbhajkwsmvbyafzrthwf.supabase.co/storage/v1/object/public/media/profiles/park-ji-hu/2026/park-ji-hu-2022-blue-dragon.jpg",
      width: 752,
      height: 938,
      orientation: "portrait",
      assetId: "park-ji-hu-2022-blue-dragon",
    },
  },
  {
    slug: "nam-joo-hyuk",
    name: "Nam Joo-hyuk",
    type: "individual",
    careerStage: "established",
    coverageLevel: "active",
    publicationState: "published",
    lastVerified: "2026-07-15",
    disciplines: ["actor", "model"],
    pillars: ["k-drama", "k-movie", "fashion-beauty"],
    agency: "Fable Company",
    debutYear: 2013,
    bio: "Actor and model working across television, film and fashion since 2013.",
    currentActivity: "He stars in the Netflix series *The East Palace*, which premieres July 17, 2026.",
    officialLinks: [
      { label: "Korean Film Council profile", url: "https://www.koreanfilm.or.kr/eng/films/index/peopleView.jsp?peopleCd=20279929" },
    ],
    hero: {
      id: "nam-joo-hyuk-east-palace-2026",
      kind: "embed",
      alt: "Nam Joo-hyuk in the official trailer for *The East Palace*",
      credit: {
        name: "Netflix",
        url: "https://www.youtube.com/watch?v=wBUkNE1l9DU",
        kind: "embed",
      },
      embedUrl: "https://www.youtube.com/watch?v=wBUkNE1l9DU",
      platform: "youtube",
      date: "2026-07-01",
    },
  },
  {
    slug: "kim-seon-ho",
    name: "Kim Seon-ho",
    type: "individual",
    careerStage: "established",
    coverageLevel: "active",
    publicationState: "published",
    lastVerified: "2026-07-15",
    disciplines: ["actor"],
    pillars: ["k-drama", "k-movie"],
    agency: "Fantagio",
    debutYear: 2009,
    bio: "Stage and screen actor whose professional work spans theater, television and film.",
    currentActivity: "He leads the Netflix romantic comedy *Can This Love Be Translated?*.",
    officialLinks: [
      { label: "Agency profile", url: "http://www.fantagio.kr/profiles/355136/" },
    ],
    hero: {
      id: "kim-seon-ho-official-2026",
      kind: "embed",
      alt: "Kim Seon-ho in an official channel video",
      credit: {
        name: "김선호 KIM SEONHO",
        url: "https://www.youtube.com/watch?v=uiW_KangJYo",
        kind: "embed",
      },
      embedUrl: "https://www.youtube.com/watch?v=uiW_KangJYo",
      platform: "youtube",
      date: "2026-04-29",
    },
  },
  {
    slug: "han-so-hee",
    name: "Han So-hee",
    type: "individual",
    careerStage: "established",
    coverageLevel: "active",
    publicationState: "published",
    lastVerified: "2026-07-15",
    disciplines: ["actor", "model"],
    pillars: ["k-drama", "k-movie", "fashion-beauty"],
    agency: "9ato Entertainment",
    debutYear: 2017,
    bio: "Actor and fashion ambassador working across television, film and luxury campaigns.",
    currentActivity: "Her current film slate includes *Project Y*.",
    officialLinks: [
      { label: "Official profile", url: "https://www.kjmana-ent.com/hansohee" },
    ],
    hero: {
      id: "han-so-hee-2025-dior-departure-hero",
      kind: "image",
      alt: "Han So-hee departing Incheon for the Dior Cruise 2026 show in May 2025",
      credit: {
        name: "티비텐 TV10",
        url: "https://commons.wikimedia.org/wiki/File:250525_Han_So_Hee_(%ED%95%9C%EC%86%8C%ED%9D%AC).png",
        kind: "licensed",
      },
      src: "https://rbhajkwsmvbyafzrthwf.supabase.co/storage/v1/object/public/media/profiles/han-so-hee/2026/han-so-hee-2025-dior-departure.png",
      width: 1350,
      height: 1080,
      orientation: "landscape",
      assetId: "han-so-hee-2025-dior-departure",
    },
  },
  {
    slug: "ahn-hyo-seop",
    name: "Ahn Hyo-seop",
    type: "individual",
    careerStage: "established",
    coverageLevel: "active",
    publicationState: "published",
    lastVerified: "2026-07-15",
    disciplines: ["actor"],
    pillars: ["k-drama", "k-movie"],
    agency: "The Present Company",
    debutYear: 2015,
    bio: "Actor with Korean and international screen roles across television, film and streaming releases.",
    currentActivity: "He leads the Netflix series *Sold Out on You*.",
    officialLinks: [
      { label: "Agency profile", url: "https://www.thepresentcompany.kr/default/artist/ahnhyoseop/" },
    ],
    hero: {
      id: "ahn-hyo-seop-netflix-2026",
      kind: "embed",
      alt: "Ahn Hyo-seop in an official Netflix Philippines video",
      credit: {
        name: "Netflix Philippines",
        url: "https://www.youtube.com/watch?v=ppx1sVvJsUY",
        kind: "embed",
      },
      embedUrl: "https://www.youtube.com/watch?v=ppx1sVvJsUY",
      platform: "youtube",
      date: "2026-04-10",
    },
  },
];
