import type { Pulse } from "../../lib/types";

export const pulses202607: Pulse[] = [
  {
    slug: "2026-07-le-sserafim-pureflow-incheon",
    heading: "LE SSERAFIM opens the PUREFLOW tour in Incheon",
    artistSlugs: ["le-sserafim"],
    pillar: "k-pop",
    date: "2026-07-12",
    body: "LE SSERAFIM completed the first two shows of the PUREFLOW tour at Inspire Arena on July 11 and 12. Huh Yunjin marked the end of the Incheon run in a post after the second concert.",
    source: {
      name: "LE SSERAFIM · Weverse",
      url: "https://weverse.io/lesserafim/artist/3-235634448?hl=ko",
      kind: "official",
    },
  },
  {
    slug: "2026-07-bts-london-return",
    heading: "BTS returns to London with the ARIRANG tour",
    artistSlugs: ["bts"],
    pillar: "k-pop",
    date: "2026-07-06",
    body: "BTS returned to London for the first of two sold-out Tottenham Hotspur Stadium shows on July 6. The stop was the group's first London concert in seven years.",
    source: {
      name: "NME",
      url: "https://www.nme.com/news/music/bts-london-tottenham-stadium-report-setlist-photos-footage-3955412",
      kind: "press",
    },
    media: {
      id: "bts-2022-white-house",
      kind: "image",
      alt: "BTS at the White House in May 2022",
      credit: {
        name: "The White House",
        url: "https://commons.wikimedia.org/wiki/File:BTS_at_the_White_House_on_May_31,_2022.jpg",
        kind: "licensed",
      },
      src: "https://rbhajkwsmvbyafzrthwf.supabase.co/storage/v1/object/public/media/profiles/bts/2026/bts-2022-white-house.jpg",
      width: 3000,
      height: 2000,
      orientation: "landscape",
      assetId: "bts-2022-white-house",
    },
  },
  {
    slug: "2026-07-twice-tour-finale-seoul",
    heading: "TWICE closes the THIS IS FOR world tour in Seoul",
    artistSlugs: ["twice"],
    pillar: "k-pop",
    date: "2026-07-12",
    body: "TWICE finished the THIS IS FOR world tour with three concerts at Seoul's KSPO Dome from July 10 through 12. The group marked the final night with an official post thanking ONCE for a year of support.",
    source: {
      name: "TWICE · X",
      url: "https://x.com/JYPETWICE/status/2076279080694014277",
      kind: "official",
    },
    media: {
      id: "twice-2024-las-vegas",
      kind: "image",
      alt: "TWICE performing in Las Vegas in 2024",
      credit: {
        name: "David Lee",
        url: "https://commons.wikimedia.org/wiki/File:TWICE_in_Las_Vegas_01.jpg",
        kind: "licensed",
      },
      src: "https://rbhajkwsmvbyafzrthwf.supabase.co/storage/v1/object/public/media/profiles/twice/2026/twice-2024-las-vegas.jpg",
      width: 4364,
      height: 2455,
      orientation: "landscape",
      assetId: "twice-2024-las-vegas",
    },
  },
  {
    slug: "2026-07-babymonster-i-like-it-video",
    heading: "BABYMONSTER releases the 'I LIKE IT' video",
    artistSlugs: ["babymonster"],
    pillar: "k-pop",
    date: "2026-07-06",
    body: "BABYMONSTER released the official music video for 'I LIKE IT'.",
    source: {
      name: "YG Entertainment",
      url: "https://yg-life.com/archives/197479?lang=en",
      kind: "official",
    },
  },
  {
    slug: "2026-07-stray-kids-run-it-uk-charts",
    heading: "Stray Kids enters two UK sales charts with 'RUN IT'",
    artistSlugs: ["stray-kids"],
    pillar: "k-pop",
    date: "2026-07-02",
    body: "'RUN IT' debuted at No. 14 on the Official Singles Sales Chart and No. 12 on the Official Singles Downloads Chart. Both results carried a first chart date of July 2.",
    source: {
      name: "Official Charts Company",
      url: "https://www.officialcharts.com/songs/stray-kids-run-it/",
      kind: "official",
    },
  },
  {
    slug: "2026-07-hearts2hearts-music-station-debut",
    heading: "Hearts2Hearts performs 'Lemon Tang' on *Music Station*",
    artistSlugs: ["hearts2hearts"],
    pillar: "k-pop",
    date: "2026-07-10",
    body: "Hearts2Hearts performed 'Lemon Tang' on the July 10 edition of *Music Station*.",
    source: {
      name: "TV Asahi · Music Station",
      url: "https://www.tv-asahi.co.jp/music/contents/m_lineup_top/0347/",
      kind: "official",
    },
  },
  {
    slug: "2026-07-seventeen-v8-goyang-live",
    heading: "SEVENTEEN unit V8 brings two live dates to Goyang",
    artistSlugs: ["seventeen"],
    pillar: "k-pop",
    date: "2026-07-12",
    body: "Weverse listed V8's Goyang live streams for July 11 and 12, with delayed streams scheduled for August 1 and 2.",
    source: {
      name: "SEVENTEEN · Weverse Concerts",
      url: "https://concerts.weverse.io/events/v8_live_goyang",
      kind: "official",
    },
  },
  {
    slug: "2026-07-kim-min-ha-hana-korea-interview",
    heading: "Kim Min-ha explains her approach to *Hana Korea*",
    artistSlugs: ["kim-min-ha"],
    pillar: "k-movie",
    date: "2026-07-03",
    body: "Kim Min-ha said she grounded her performance in testimony from North Korean defectors and treated the story's real letters with particular care. She hoped *Hana Korea* would offer comfort to people struggling to adapt and survive.",
    source: {
      name: "Yonhap News Agency",
      url: "https://en.yna.co.kr/view/AEN20260703009900315",
      kind: "wire",
    },
    media: {
      id: "kim-min-ha-2024-love-your-w",
      kind: "image",
      alt: "Kim Min-ha in October 2024",
      credit: {
        name: "티비텐 TV10",
        url: "https://commons.wikimedia.org/wiki/File:Kim_Min-ha_in_October_2024.png",
        kind: "licensed",
      },
      src: "https://rbhajkwsmvbyafzrthwf.supabase.co/storage/v1/object/public/media/profiles/kim-min-ha/2026/kim-min-ha-2024-love-your-w.png",
      width: 2588,
      height: 3604,
      orientation: "portrait",
      assetId: "kim-min-ha-2024-love-your-w",
    },
  },
  {
    slug: "2026-07-jung-hoyeon-hope-press-screening",
    heading: "Jung Ho-yeon presents *Hope* at its Korean media screening",
    artistSlugs: ["jung-hoyeon"],
    pillar: "k-movie",
    date: "2026-07-06",
    body: "Jung Ho-yeon joined director Na Hong-jin and cast members Hwang Jung-min and Zo In-sung at the *Hope* media screening and news conference at Megabox COEX in Seoul.",
    source: {
      name: "Korea.net",
      url: "https://www.korea.net/NewsFocus/Culture/view?articleId=295871",
      kind: "official",
    },
    media: {
      id: "jung-hoyeon-2021-portrait",
      kind: "image",
      alt: "Jung Ho-yeon in 2021",
      credit: {
        name: "Marie Claire Korea",
        url: "https://commons.wikimedia.org/wiki/File:HoYeon_Jung_in_November_2021.jpg",
        kind: "licensed",
      },
      src: "https://rbhajkwsmvbyafzrthwf.supabase.co/storage/v1/object/public/media/profiles/jung-hoyeon/2026/jung-hoyeon-2021-portrait.jpg",
      width: 3544,
      height: 4320,
      orientation: "portrait",
      assetId: "jung-hoyeon-2021-portrait",
    },
  },
  {
    slug: "2026-07-east-palace-press-conference",
    heading: "Roh Yoon-seo and Nam Joo-hyuk present *The East Palace*",
    artistSlugs: ["roh-yoon-seo", "nam-joo-hyuk"],
    pillar: "k-drama",
    date: "2026-07-08",
    body: "Roh Yoon-seo and Nam Joo-hyuk attended the Seoul press conference for *The East Palace*. The leads introduced the fantasy series ahead of its July 17 Netflix premiere.",
    source: {
      name: "Yonhap News Agency",
      url: "https://en.yna.co.kr/view/AEN20260708006900315",
      kind: "wire",
    },
  },
  {
    slug: "2026-07-byeon-woo-seok-secret-library-seoul",
    heading: "Byeon Woo-seok opens The Secret Library with a sold-out Seoul run",
    artistSlugs: ["byeon-woo-seok"],
    pillar: "k-drama",
    date: "2026-07-05",
    body: "Byeon Woo-seok opened The Secret Library fan-meeting tour with sold-out shows at Jamsil Indoor Gymnasium on July 4 and 5. The Seoul engagement was the first stop on his second Asia fan-meeting tour.",
    source: {
      name: "SBS Star",
      url: "https://news.sbs.co.kr/amp/news.amp?news_id=N1008645085",
      kind: "press",
    },
    media: {
      id: "byeon-woo-seok-2024-portrait",
      kind: "image",
      alt: "Byeon Woo-seok at a 2024 photocall",
      credit: {
        name: "티비텐 TV10",
        url: "https://commons.wikimedia.org/wiki/File:240909_Byeon_Woo_Seok_%28%EB%B3%80%EC%9A%B0%EC%84%9D%29.png",
        kind: "licensed",
      },
      src: "https://rbhajkwsmvbyafzrthwf.supabase.co/storage/v1/object/public/media/profiles/byeon-woo-seok/2026/byeon-woo-seok-2024-portrait.png",
      width: 1080,
      height: 1350,
      orientation: "portrait",
      assetId: "byeon-woo-seok-2024-portrait",
    },
  },
  {
    slug: "2026-07-blackpink-jennie-dracula-hot-100",
    heading: "Jennie's 'Dracula' remix reaches the Hot 100 top five",
    artistSlugs: ["blackpink"],
    pillar: "k-pop",
    date: "2026-07-14",
    body: "Tame Impala's 'Dracula' remix featuring Jennie rose to No. 5 on the Billboard Hot 100. The result gave the BLACKPINK member her first top-five entry on the chart.",
    source: {
      name: "Yonhap News Agency",
      url: "https://en.yna.co.kr/view/AEN20260714002500315",
      kind: "wire",
    },
  },
  {
    slug: "2026-07-bts-british-museum-gallery-trail",
    heading: "BTS partners with the British Museum on a Korean Gallery Trail",
    artistSlugs: ["bts"],
    pillar: "k-pop",
    date: "2026-07-08",
    body: "BTS and the British Museum launched a trail connecting objects in the museum's Korean Gallery with themes from the group's music. The visitor program was underway when the collaboration was announced.",
    source: {
      name: "Yonhap News Agency",
      url: "https://en.yna.co.kr/view/AEN20260708007600315",
      kind: "wire",
    },
  },
  {
    slug: "2026-07-twice-stray-kids-recording-academy",
    heading: "TWICE and Stray Kids receive Recording Academy voting invitations",
    artistSlugs: ["twice", "stray-kids"],
    pillar: "k-pop",
    date: "2026-07-14",
    body: "All members of TWICE and Stray Kids received invitations to join the Recording Academy as voting members. JYP Entertainment announced the invitations alongside Park Jin-young's invitation.",
    source: {
      name: "Yonhap News Agency",
      url: "https://en.yna.co.kr/view/AEN20260714005900315",
      kind: "wire",
    },
  },
  {
    slug: "2026-07-ateez-golden-hour-part5-first-week",
    heading: "ATEEZ sets a new first-week sales record",
    artistSlugs: ["ateez"],
    pillar: "k-pop",
    date: "2026-07-02",
    body: "*GOLDEN HOUR : Part.5* sold 1,885,712 copies during its first Hanteo tracking week, which closed July 2. The total set a new personal record for ATEEZ.",
    source: {
      name: "Hanteo News",
      url: "https://www.hanteonews.com/en/article/92974",
      kind: "official",
    },
  },
  {
    slug: "2026-07-hearts2hearts-lemon-tang-first-win",
    heading: "Hearts2Hearts earns its first 'Lemon Tang' trophy",
    artistSlugs: ["hearts2hearts"],
    pillar: "k-pop",
    date: "2026-07-02",
    body: "Hearts2Hearts won the July 2 episode of *M Countdown* with 'Lemon Tang'. The song earned 6,431 points for its first music-show trophy.",
    source: {
      name: "Soompi",
      url: "https://www.soompi.com/article/1851894wpp/watch-hearts2hearts-takes-1st-win-for-lemon-tang-on-m-countdown-performances-by-seventeens-v8-riize-and-more",
      kind: "press",
    },
  },
  {
    slug: "2026-07-illit-aespa-hanteo-country-charts",
    heading: "ILLIT and aespa lead Hanteo country charts",
    artistSlugs: ["illit", "aespa"],
    pillar: "k-pop",
    date: "2026-07-10",
    body: "ILLIT's *MAMIHLAPINATAPAI* led Hanteo's Japan chart for the first week of July. aespa's *LEMONADE* held No. 1 in China for a sixth consecutive week.",
    source: {
      name: "Hanteo News",
      url: "https://www.hanteonews.com/en/article/93087",
      kind: "official",
    },
  },
  {
    slug: "2026-07-ive-circle-midyear",
    heading: "IVE places on both Circle midyear charts",
    artistSlugs: ["ive"],
    pillar: "k-pop",
    date: "2026-07-14",
    body: "Circle's first-half charts placed 'BANG BANG' at No. 7 on the Digital Chart and *REVIVE+* at No. 15 on the Album Chart. The published rankings measured activity through June 30.",
    source: {
      name: "Soompi · Circle Chart",
      url: "https://www.soompi.com/article/1854722wpp/circle-chart-reveals-midyear-album-and-digital-charts-for-1st-half-of-2026",
      kind: "press",
    },
  },
  {
    slug: "2026-07-cortis-circle-midyear",
    heading: "CORTIS puts three entries on Circle's midyear album list",
    artistSlugs: ["cortis"],
    pillar: "k-pop",
    date: "2026-07-14",
    body: "*GREENGREEN* ranked No. 3 on Circle's first-half Album Chart with 2,031,256 copies. Its Weverse edition ranked No. 19, while *COLOR OUTSIDE THE LINES* ranked No. 24 in data measured through June 30.",
    source: {
      name: "Soompi · Circle Chart",
      url: "https://www.soompi.com/article/1854722wpp/circle-chart-reveals-midyear-album-and-digital-charts-for-1st-half-of-2026",
      kind: "press",
    },
  },
  {
    slug: "2026-07-rookie-groups-circle-midyear",
    heading: "TWS, RIIZE and BOYNEXTDOOR clear Circle's midyear top 12",
    artistSlugs: ["tws", "riize", "boynextdoor"],
    pillar: "k-pop",
    date: "2026-07-14",
    body: "Circle's first-half Album Chart ranked TWS's *NO TRAGEDY* at No. 9, RIIZE's *II* at No. 10 and BOYNEXTDOOR's *HOME* at No. 12. The published list measured sales through June 30.",
    source: {
      name: "Soompi · Circle Chart",
      url: "https://www.soompi.com/article/1854722wpp/circle-chart-reveals-midyear-album-and-digital-charts-for-1st-half-of-2026",
      kind: "press",
    },
  },
  {
    slug: "2026-07-park-eun-bin-spooky-in-love-press-conference",
    heading: "Park Eun-bin presents *Spooky in Love* in Seoul",
    artistSlugs: ["park-eun-bin"],
    pillar: "k-drama",
    date: "2026-07-14",
    body: "Park Eun-bin joined the cast and director of *Spooky in Love* at the series press conference in Seoul. She described a television adaptation with a substantially expanded story ahead of its July 18 premiere.",
    source: {
      name: "The Korea Times",
      url: "https://www.koreatimes.co.kr/amp/entertainment/shows-dramas/20260714/spooky-in-love-reimagines-hit-film-with-supernatural-twist",
      kind: "press",
    },
    media: {
      id: "park-eun-bin-2025-portrait",
      kind: "image",
      alt: "Park Eun-bin at a 2025 press conference",
      credit: {
        name: "티비텐 TV10",
        url: "https://commons.wikimedia.org/wiki/File:250317_Park_Eun_Bin_%28%EB%B0%95%EC%9D%80%EB%B9%88%29.png",
        kind: "licensed",
      },
      src: "https://rbhajkwsmvbyafzrthwf.supabase.co/storage/v1/object/public/media/profiles/park-eun-bin/2026/park-eun-bin-2025-portrait.png",
      width: 1080,
      height: 1349,
      orientation: "portrait",
      assetId: "park-eun-bin-2025-portrait",
    },
  },
];
