#!/usr/bin/env node

import { createHash } from "node:crypto";
import { mkdirSync, readdirSync, writeFileSync } from "node:fs";
import { join } from "node:path";

import { articles } from "../src/content/articles";
import { clips } from "../src/content/clips";
import { editions } from "../src/content/editions/index";
import { events } from "../src/content/events";
import { galleries } from "../src/content/galleries";
import { NOW } from "../src/content/now";
import { predictions } from "../src/content/predictions";
import { artists } from "../src/content/profiles";
import { pulses } from "../src/content/pulses/index";
import { rankings } from "../src/content/rankings";
import { flattenEdition } from "../src/lib/edition/constraints";
import { buildEdition, type EditionEngineInput } from "../src/lib/edition/engine";

const GENERATOR_VERSION = "1.0.0";
const EDITIONS_DIR = join(process.cwd(), "src", "content", "editions");

function canonicalize(value: unknown): unknown {
  if (Array.isArray(value)) return value.map(canonicalize);
  if (value && typeof value === "object") {
    return Object.fromEntries(
      Object.entries(value as Record<string, unknown>)
        .filter(([, child]) => child !== undefined)
        .sort(([left], [right]) => left.localeCompare(right))
        .map(([key, child]) => [key, canonicalize(child)]),
    );
  }
  return value;
}

function inventoryHash(input: EditionEngineInput): string {
  return createHash("sha256").update(JSON.stringify(canonicalize(input))).digest("hex");
}

function editionExportName(id: string): string {
  return `edition${id.replace("-", "")}`;
}

function editionSource(id: string, hash: string, edition: ReturnType<typeof buildEdition>): string {
  return [
    `// Generated by MyKStars edition engine v${GENERATOR_VERSION}.`,
    `// Inventory SHA-256: ${hash}`,
    `// Regenerate with npm run gen:edition. Do not hand-edit this artifact.`,
    `import type { FeedEdition } from "../../lib/types";`,
    "",
    `export const ${editionExportName(id)}: FeedEdition = ${JSON.stringify(edition, null, 2)};`,
    "",
  ].join("\n");
}

function indexSource(ids: readonly string[]): string {
  const imports = ids.map((id) => `import { ${editionExportName(id)} } from "./${id}";`);
  const entries = ids.map((id) => `  ${editionExportName(id)},`);
  return [
    `import type { FeedEdition } from "../../lib/types";`,
    ...imports,
    "",
    `export const editions: FeedEdition[] = [`,
    ...entries,
    `];`,
    "",
  ].join("\n");
}

const args = process.argv.slice(2);
if (args.length > 2) {
  console.error("Usage: npm run gen:edition -- [YYYY-MM] [publishedAt]");
  process.exit(1);
}

const editionId = args[0] ?? NOW.slice(0, 7);
const publishedAt = args[1] ?? NOW;
const input: EditionEngineInput = {
  publishedAt,
  artists,
  pulses,
  clips,
  galleries,
  predictions,
  events,
  rankings,
  articles,
  trailingEditions: editions.filter((edition) => edition.id < editionId),
};

try {
  const edition = buildEdition(input, editionId);
  const hash = inventoryHash(input);
  mkdirSync(EDITIONS_DIR, { recursive: true });
  const editionFile = join(EDITIONS_DIR, `${editionId}.ts`);
  writeFileSync(editionFile, editionSource(editionId, hash, edition), "utf8");

  const editionIds = readdirSync(EDITIONS_DIR)
    .filter((name) => /^\d{4}-(0[1-9]|1[0-2])\.ts$/.test(name))
    .map((name) => name.slice(0, -3))
    .sort();
  writeFileSync(join(EDITIONS_DIR, "index.ts"), indexSource(editionIds), "utf8");
  console.log(`Generated ${editionFile} (${flattenEdition(edition).length} items; inventory ${hash.slice(0, 12)}).`);
} catch (error) {
  const message = error instanceof Error ? error.message : String(error);
  console.error(`Edition generation refused for ${editionId}: ${message}`);
  process.exit(1);
}
