#!/usr/bin/env node

import { mkdirSync, writeFileSync } from "node:fs";
import { join } from "node:path";

import { flattenEdition } from "../src/lib/edition/constraints";
import { buildEdition, type EditionEngineInput } from "../src/lib/edition/engine";
import {
  buildEditionProvenance,
} from "../src/lib/edition/provenance";
import type { FeedEdition } from "../src/lib/domain/editions";
import {
  NOW,
  currentEditionInventory,
  editions,
} from "./edition-content";
import { writeGeneratedIndexes } from "./generated-indexes";

const GENERATOR_VERSION = "2.0.0";
const EDITIONS_DIR = join(process.cwd(), "src", "content", "editions");

type GeneratedEdition = FeedEdition;

function editionExportName(id: string): string {
  return `edition${id.replace("-", "")}`;
}

export function editionSource(id: string, hash: string, edition: GeneratedEdition): string {
  return [
    `// Generated by MyKStars edition engine v${GENERATOR_VERSION}.`,
    `// Inventory SHA-256: ${hash}`,
    `// Regenerate with npm run gen:edition. Do not hand-edit this artifact.`,
    `import type { FeedEdition } from "../../lib/types";`,
    "",
    `export const ${editionExportName(id)}: FeedEdition = ${JSON.stringify(edition, null, 2)};`,
    "",
  ].join("\n");
}

const args = process.argv.slice(2);
if (args.length > 2) {
  console.error("Usage: npm run gen:edition -- [YYYY-MM] [publishedAt]");
  process.exit(1);
}

const editionId = args[0] ?? NOW.slice(0, 7);
const publishedAt = args[1] ?? NOW;
const input: EditionEngineInput = {
  publishedAt,
  ...currentEditionInventory,
  trailingEditions: editions.filter((edition) => edition.id < editionId),
};

try {
  const edition = buildEdition(input, editionId);
  const provenance = {
    ...buildEditionProvenance({ ...input, editionId }),
    activeArtistSlugs: [
      ...edition.spotlight.anchors,
      ...edition.spotlight.weeks.flat(),
    ],
  };
  const artifact: GeneratedEdition = { ...edition, provenance };
  const hash = provenance.inventoryHash;
  mkdirSync(EDITIONS_DIR, { recursive: true });
  const editionFile = join(EDITIONS_DIR, `${editionId}.ts`);
  writeFileSync(editionFile, editionSource(editionId, hash, artifact), "utf8");
  writeGeneratedIndexes();
  console.log(`Generated ${editionFile} (${flattenEdition(edition).length} items; inventory ${hash.slice(0, 12)}).`);
} catch (error) {
  const message = error instanceof Error ? error.message : String(error);
  console.error(`Edition generation refused for ${editionId}: ${message}`);
  process.exit(1);
}
