import { basename } from "node:path";

import { readTypeScriptSource, ts } from "./typescript-source";

export interface GeneratedEditionArtifact {
  edition: unknown;
  exportName: string;
  inventoryHash: string;
  generatorVersion: string;
}

export interface GeneratedEditionInspection {
  artifact?: GeneratedEditionArtifact;
  errors: string[];
}

const HEADER = /^\/\/ Generated by MyKStars edition engine v(\d+\.\d+\.\d+)\.\r?\n\/\/ Inventory SHA-256: ([a-f0-9]{64})\r?\n\/\/ Regenerate with npm run gen:edition\. Do not hand-edit this artifact\.\r?\n/;

function hasModifier(node: ts.Node, kind: ts.SyntaxKind): boolean {
  return Boolean(ts.getModifiers(node as ts.HasModifiers)?.some((modifier) => modifier.kind === kind));
}

export function inspectGeneratedEditionSource(file: string): GeneratedEditionInspection {
  const errors: string[] = [];
  const parsed = readTypeScriptSource(file);
  const source = parsed.text;
  const header = HEADER.exec(source);
  if (!header) {
    errors.push("generated header must contain the exact engine, inventory hash, and regeneration lines");
  }

  const sourceFile = parsed.sourceFile;
  const imports = sourceFile.statements.filter(ts.isImportDeclaration);
  const variables = sourceFile.statements.filter(ts.isVariableStatement);
  const unexpected = sourceFile.statements.filter((statement) =>
    !ts.isImportDeclaration(statement) && !ts.isVariableStatement(statement));
  if (unexpected.length > 0) errors.push("artifact contains statements outside type imports and its edition export");
  if (imports.length < 1 || imports.some((statement) => !statement.importClause?.isTypeOnly)) {
    errors.push("artifact imports must be type-only");
  }
  if (variables.length !== 1) errors.push("artifact must contain exactly one exported const declaration");

  const statement = variables[0];
  const declaration = statement?.declarationList.declarations[0];
  if (statement && (
    !(statement.declarationList.flags & ts.NodeFlags.Const) ||
    statement.declarationList.declarations.length !== 1 ||
    !hasModifier(statement, ts.SyntaxKind.ExportKeyword)
  )) {
    errors.push("edition declaration must be one exported const");
  }
  if (!declaration || !ts.isIdentifier(declaration.name)) {
    errors.push("edition declaration needs a plain identifier");
  }

  const id = basename(file, ".ts");
  const expectedExport = `edition${id.replace("-", "")}`;
  const exportName = declaration && ts.isIdentifier(declaration.name) ? declaration.name.text : "";
  if (exportName !== expectedExport) {
    errors.push(`edition export ${exportName || "<missing>"} does not match ${expectedExport}`);
  }
  if (!declaration?.type || !declaration.type.getText(sourceFile).startsWith("FeedEdition")) {
    errors.push("edition export must retain an explicit FeedEdition type contract");
  }
  if (!declaration?.initializer || !ts.isObjectLiteralExpression(declaration.initializer)) {
    errors.push("edition export initializer must be a plain object literal");
  }

  let edition: unknown;
  if (declaration?.initializer && ts.isObjectLiteralExpression(declaration.initializer)) {
    try {
      edition = JSON.parse(declaration.initializer.getText(sourceFile));
    } catch (error) {
      errors.push(`edition initializer is outside the generated JSON grammar: ${error instanceof Error ? error.message : String(error)}`);
    }
  }

  if (errors.length > 0 || edition === undefined || !header) return { errors };
  return {
    errors,
    artifact: {
      edition,
      exportName,
      generatorVersion: header[1],
      inventoryHash: header[2],
    },
  };
}
