// Generates every brand asset the site needs from the two source logos in /brand:
//   - public/logos/mykstars-lockup.svg  (icon + wordmark, background stripped)
//   - public/logos/mykstars-mark.svg    (icon glyph only, background stripped)
//   - src/lib/brand.ts                  (inline SVG strings for the React UI + OG card)
//   - src/app/icon.svg                  (vector favicon: glyph padded on ink)
//   - src/app/apple-icon.png            (180, glyph padded on ink)
//   - src/app/favicon.ico               (16/32/48 PNG-in-ICO)
//   - public/icons/icon-{192,512}.png + icon-maskable-512.png
//
// sharp rasterizes SVG -> PNG but cannot emit .ico, so the ICO container is hand-built.
// Re-run after the source logos change:  node scripts/generate-icons.mjs
import sharp from "sharp";
import { readFileSync, writeFileSync, mkdirSync } from "node:fs";
import { fileURLToPath } from "node:url";
import { dirname, join } from "node:path";

const ROOT = join(dirname(fileURLToPath(import.meta.url)), "..");
const p = (...s) => join(ROOT, ...s);
const INK = "#0e0e0e";

for (const d of ["public/logos", "public/icons"]) mkdirSync(p(d), { recursive: true });

// --- Read sources -----------------------------------------------------------
const lockupSrc = readFileSync(p("brand/lockup.svg"), "utf8");
const markSrc = readFileSync(p("brand/mark.svg"), "utf8");

// --- Lockup: drop the two background rects + clip-paths, keep the artwork ----
// Everything from the artwork group to just before </svg>, minus clip references.
const lockupInner = lockupSrc
  .slice(lockupSrc.indexOf('<g transform="matrix'), lockupSrc.lastIndexOf("</svg>"))
  .replace(/\s*clip-path="url\(#[^)]*\)"/g, "");
const LOCKUP_VIEWBOX = "0 0 1500 600";
const lockupSvg = `<svg xmlns="http://www.w3.org/2000/svg" viewBox="${LOCKUP_VIEWBOX}">${lockupInner}</svg>`;

// --- Mark: pull the single crimson glyph path (keeps its fill-rule) ----------
const markPath = markSrc.match(/<path fill="#cc001e"[\s\S]*?\/>/)[0];
const markSvg = `<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 1500 1500">${markPath}</svg>`;

// --- Square icon composites: glyph centered on an ink field ------------------
// Source glyph bounding box (from mark.svg clip bounds) -> center for scaling.
const CX = 740.5;
const CY = 750;
const composite = (scale) =>
  `<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 1500 1500" width="1500" height="1500">` +
  `<rect width="1500" height="1500" fill="${INK}"/>` +
  `<g transform="translate(750 750) scale(${scale}) translate(${-CX} ${-CY})">${markPath}</g>` +
  `</svg>`;
const iconSvg = composite(0.78); // standard padding (tabs, app icons)
const maskableSvg = composite(0.6); // extra safe-area padding (Android maskable)

// --- Write SVG + TS artifacts ------------------------------------------------
writeFileSync(p("public/logos/mykstars-lockup.svg"), lockupSvg);
writeFileSync(p("public/logos/mykstars-mark.svg"), markSvg);
writeFileSync(p("src/app/icon.svg"), iconSvg);
writeFileSync(
  p("src/lib/brand.ts"),
  `// Generated by scripts/generate-icons.mjs from /brand. Do not edit by hand.\n` +
    `export const LOCKUP_VIEWBOX = ${JSON.stringify(LOCKUP_VIEWBOX)};\n` +
    `export const LOCKUP_INNER = ${JSON.stringify(lockupInner)};\n` +
    `export const LOCKUP_SVG = ${JSON.stringify('<svg xmlns="http://www.w3.org/2000/svg" viewBox="')} + LOCKUP_VIEWBOX + ${JSON.stringify('">')} + LOCKUP_INNER + ${JSON.stringify("</svg>")};\n`,
);

// --- Rasterize PNGs ----------------------------------------------------------
const iconBuf = Buffer.from(iconSvg);
const png = (svg, size) => sharp(Buffer.from(svg)).resize(size, size).png().toBuffer();

await Promise.all([
  sharp(iconBuf).resize(180, 180).png().toFile(p("src/app/apple-icon.png")),
  sharp(iconBuf).resize(192, 192).png().toFile(p("public/icons/icon-192.png")),
  sharp(iconBuf).resize(512, 512).png().toFile(p("public/icons/icon-512.png")),
  sharp(Buffer.from(maskableSvg))
    .resize(512, 512)
    .png()
    .toFile(p("public/icons/icon-maskable-512.png")),
]);

// --- favicon.ico (PNG-in-ICO: ICONDIR + entries + payloads) ------------------
const icoSizes = [16, 32, 48];
const icoPngs = await Promise.all(icoSizes.map((s) => png(iconSvg, s)));
const header = Buffer.alloc(6);
header.writeUInt16LE(0, 0); // reserved
header.writeUInt16LE(1, 2); // type: icon
header.writeUInt16LE(icoPngs.length, 4);
const entries = Buffer.alloc(16 * icoPngs.length);
let offset = 6 + 16 * icoPngs.length;
icoPngs.forEach((img, i) => {
  const e = i * 16;
  const s = icoSizes[i];
  entries.writeUInt8(s >= 256 ? 0 : s, e); // width
  entries.writeUInt8(s >= 256 ? 0 : s, e + 1); // height
  entries.writeUInt8(0, e + 2); // palette
  entries.writeUInt8(0, e + 3); // reserved
  entries.writeUInt16LE(1, e + 4); // color planes
  entries.writeUInt16LE(32, e + 6); // bits per pixel
  entries.writeUInt32LE(img.length, e + 8);
  entries.writeUInt32LE(offset, e + 12);
  offset += img.length;
});
writeFileSync(p("src/app/favicon.ico"), Buffer.concat([header, entries, ...icoPngs]));

console.log("Brand assets generated:");
for (const f of [
  "public/logos/mykstars-lockup.svg",
  "public/logos/mykstars-mark.svg",
  "src/lib/brand.ts",
  "src/app/icon.svg",
  "src/app/apple-icon.png",
  "src/app/favicon.ico",
  "public/icons/icon-192.png",
  "public/icons/icon-512.png",
  "public/icons/icon-maskable-512.png",
]) {
  console.log("  " + f);
}
